// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BoostRequestT struct {
	Token string `json:"token"`
	DeviceId uint32 `json:"device_id"`
	SenderId string `json:"sender_id"`
	ChangeAddress []byte `json:"change_address"`
	PricePerHead uint32 `json:"price_per_head"`
	Query *BoostQueryT `json:"query"`
	BoostMessage []byte `json:"boost_message"`
	S1 []byte `json:"s1"`
	Media []byte `json:"media"`
	Tx []byte `json:"tx"`
	InputSats uint64 `json:"input_sats"`
}

func (t *BoostRequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	tokenOffset := flatbuffers.UOffsetT(0)
	if t.Token != "" {
		tokenOffset = builder.CreateString(t.Token)
	}
	senderIdOffset := flatbuffers.UOffsetT(0)
	if t.SenderId != "" {
		senderIdOffset = builder.CreateString(t.SenderId)
	}
	changeAddressOffset := flatbuffers.UOffsetT(0)
	if t.ChangeAddress != nil {
		changeAddressOffset = builder.CreateByteString(t.ChangeAddress)
	}
	queryOffset := t.Query.Pack(builder)
	boostMessageOffset := flatbuffers.UOffsetT(0)
	if t.BoostMessage != nil {
		boostMessageOffset = builder.CreateByteString(t.BoostMessage)
	}
	s1Offset := flatbuffers.UOffsetT(0)
	if t.S1 != nil {
		s1Offset = builder.CreateByteString(t.S1)
	}
	mediaOffset := flatbuffers.UOffsetT(0)
	if t.Media != nil {
		mediaOffset = builder.CreateByteString(t.Media)
	}
	txOffset := flatbuffers.UOffsetT(0)
	if t.Tx != nil {
		txOffset = builder.CreateByteString(t.Tx)
	}
	BoostRequestStart(builder)
	BoostRequestAddToken(builder, tokenOffset)
	BoostRequestAddDeviceId(builder, t.DeviceId)
	BoostRequestAddSenderId(builder, senderIdOffset)
	BoostRequestAddChangeAddress(builder, changeAddressOffset)
	BoostRequestAddPricePerHead(builder, t.PricePerHead)
	BoostRequestAddQuery(builder, queryOffset)
	BoostRequestAddBoostMessage(builder, boostMessageOffset)
	BoostRequestAddS1(builder, s1Offset)
	BoostRequestAddMedia(builder, mediaOffset)
	BoostRequestAddTx(builder, txOffset)
	BoostRequestAddInputSats(builder, t.InputSats)
	return BoostRequestEnd(builder)
}

func (rcv *BoostRequest) UnPackTo(t *BoostRequestT) {
	t.Token = string(rcv.Token())
	t.DeviceId = rcv.DeviceId()
	t.SenderId = string(rcv.SenderId())
	t.ChangeAddress = rcv.ChangeAddressBytes()
	t.PricePerHead = rcv.PricePerHead()
	t.Query = rcv.Query(nil).UnPack()
	t.BoostMessage = rcv.BoostMessageBytes()
	t.S1 = rcv.S1Bytes()
	t.Media = rcv.MediaBytes()
	t.Tx = rcv.TxBytes()
	t.InputSats = rcv.InputSats()
}

func (rcv *BoostRequest) UnPack() *BoostRequestT {
	if rcv == nil {
		return nil
	}
	t := &BoostRequestT{}
	rcv.UnPackTo(t)
	return t
}

type BoostRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsBoostRequest(buf []byte, offset flatbuffers.UOffsetT) *BoostRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BoostRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishBoostRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsBoostRequest(buf []byte, offset flatbuffers.UOffsetT) *BoostRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BoostRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBoostRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *BoostRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BoostRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BoostRequest) Token() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BoostRequest) DeviceId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BoostRequest) MutateDeviceId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *BoostRequest) SenderId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BoostRequest) ChangeAddress(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *BoostRequest) ChangeAddressLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *BoostRequest) ChangeAddressBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BoostRequest) MutateChangeAddress(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *BoostRequest) PricePerHead() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BoostRequest) MutatePricePerHead(n uint32) bool {
	return rcv._tab.MutateUint32Slot(12, n)
}

func (rcv *BoostRequest) Query(obj *BoostQuery) *BoostQuery {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(BoostQuery)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *BoostRequest) BoostMessage(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *BoostRequest) BoostMessageLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *BoostRequest) BoostMessageBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BoostRequest) MutateBoostMessage(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *BoostRequest) S1(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *BoostRequest) S1Length() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *BoostRequest) S1Bytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BoostRequest) MutateS1(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *BoostRequest) Media(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *BoostRequest) MediaLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *BoostRequest) MediaBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BoostRequest) MutateMedia(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *BoostRequest) Tx(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *BoostRequest) TxLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *BoostRequest) TxBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BoostRequest) MutateTx(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *BoostRequest) InputSats() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BoostRequest) MutateInputSats(n uint64) bool {
	return rcv._tab.MutateUint64Slot(24, n)
}

func BoostRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(11)
}
func BoostRequestAddToken(builder *flatbuffers.Builder, token flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(token), 0)
}
func BoostRequestAddDeviceId(builder *flatbuffers.Builder, deviceId uint32) {
	builder.PrependUint32Slot(1, deviceId, 0)
}
func BoostRequestAddSenderId(builder *flatbuffers.Builder, senderId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(senderId), 0)
}
func BoostRequestAddChangeAddress(builder *flatbuffers.Builder, changeAddress flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(changeAddress), 0)
}
func BoostRequestStartChangeAddressVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func BoostRequestAddPricePerHead(builder *flatbuffers.Builder, pricePerHead uint32) {
	builder.PrependUint32Slot(4, pricePerHead, 0)
}
func BoostRequestAddQuery(builder *flatbuffers.Builder, query flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(query), 0)
}
func BoostRequestAddBoostMessage(builder *flatbuffers.Builder, boostMessage flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(boostMessage), 0)
}
func BoostRequestStartBoostMessageVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func BoostRequestAddS1(builder *flatbuffers.Builder, s1 flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(s1), 0)
}
func BoostRequestStartS1Vector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func BoostRequestAddMedia(builder *flatbuffers.Builder, media flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(media), 0)
}
func BoostRequestStartMediaVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func BoostRequestAddTx(builder *flatbuffers.Builder, tx flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(tx), 0)
}
func BoostRequestStartTxVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func BoostRequestAddInputSats(builder *flatbuffers.Builder, inputSats uint64) {
	builder.PrependUint64Slot(10, inputSats, 0)
}
func BoostRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
