// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BoostQueryT struct {
	Areas []*AreaT `json:"areas"`
	Genders []string `json:"genders"`
	Interests []string `json:"interests"`
	Lim uint64 `json:"lim"`
	MaxAge byte `json:"max_age"`
	MinAge byte `json:"min_age"`
	Countries []string `json:"countries"`
}

func (t *BoostQueryT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	areasOffset := flatbuffers.UOffsetT(0)
	if t.Areas != nil {
		areasLength := len(t.Areas)
		areasOffsets := make([]flatbuffers.UOffsetT, areasLength)
		for j := 0; j < areasLength; j++ {
			areasOffsets[j] = t.Areas[j].Pack(builder)
		}
		BoostQueryStartAreasVector(builder, areasLength)
		for j := areasLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(areasOffsets[j])
		}
		areasOffset = builder.EndVector(areasLength)
	}
	gendersOffset := flatbuffers.UOffsetT(0)
	if t.Genders != nil {
		gendersLength := len(t.Genders)
		gendersOffsets := make([]flatbuffers.UOffsetT, gendersLength)
		for j := 0; j < gendersLength; j++ {
			gendersOffsets[j] = builder.CreateString(t.Genders[j])
		}
		BoostQueryStartGendersVector(builder, gendersLength)
		for j := gendersLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(gendersOffsets[j])
		}
		gendersOffset = builder.EndVector(gendersLength)
	}
	interestsOffset := flatbuffers.UOffsetT(0)
	if t.Interests != nil {
		interestsLength := len(t.Interests)
		interestsOffsets := make([]flatbuffers.UOffsetT, interestsLength)
		for j := 0; j < interestsLength; j++ {
			interestsOffsets[j] = builder.CreateString(t.Interests[j])
		}
		BoostQueryStartInterestsVector(builder, interestsLength)
		for j := interestsLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(interestsOffsets[j])
		}
		interestsOffset = builder.EndVector(interestsLength)
	}
	countriesOffset := flatbuffers.UOffsetT(0)
	if t.Countries != nil {
		countriesLength := len(t.Countries)
		countriesOffsets := make([]flatbuffers.UOffsetT, countriesLength)
		for j := 0; j < countriesLength; j++ {
			countriesOffsets[j] = builder.CreateString(t.Countries[j])
		}
		BoostQueryStartCountriesVector(builder, countriesLength)
		for j := countriesLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(countriesOffsets[j])
		}
		countriesOffset = builder.EndVector(countriesLength)
	}
	BoostQueryStart(builder)
	BoostQueryAddAreas(builder, areasOffset)
	BoostQueryAddGenders(builder, gendersOffset)
	BoostQueryAddInterests(builder, interestsOffset)
	BoostQueryAddLim(builder, t.Lim)
	BoostQueryAddMaxAge(builder, t.MaxAge)
	BoostQueryAddMinAge(builder, t.MinAge)
	BoostQueryAddCountries(builder, countriesOffset)
	return BoostQueryEnd(builder)
}

func (rcv *BoostQuery) UnPackTo(t *BoostQueryT) {
	areasLength := rcv.AreasLength()
	t.Areas = make([]*AreaT, areasLength)
	for j := 0; j < areasLength; j++ {
		x := Area{}
		rcv.Areas(&x, j)
		t.Areas[j] = x.UnPack()
	}
	gendersLength := rcv.GendersLength()
	t.Genders = make([]string, gendersLength)
	for j := 0; j < gendersLength; j++ {
		t.Genders[j] = string(rcv.Genders(j))
	}
	interestsLength := rcv.InterestsLength()
	t.Interests = make([]string, interestsLength)
	for j := 0; j < interestsLength; j++ {
		t.Interests[j] = string(rcv.Interests(j))
	}
	t.Lim = rcv.Lim()
	t.MaxAge = rcv.MaxAge()
	t.MinAge = rcv.MinAge()
	countriesLength := rcv.CountriesLength()
	t.Countries = make([]string, countriesLength)
	for j := 0; j < countriesLength; j++ {
		t.Countries[j] = string(rcv.Countries(j))
	}
}

func (rcv *BoostQuery) UnPack() *BoostQueryT {
	if rcv == nil {
		return nil
	}
	t := &BoostQueryT{}
	rcv.UnPackTo(t)
	return t
}

type BoostQuery struct {
	_tab flatbuffers.Table
}

func GetRootAsBoostQuery(buf []byte, offset flatbuffers.UOffsetT) *BoostQuery {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BoostQuery{}
	x.Init(buf, n+offset)
	return x
}

func FinishBoostQueryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsBoostQuery(buf []byte, offset flatbuffers.UOffsetT) *BoostQuery {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BoostQuery{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBoostQueryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *BoostQuery) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BoostQuery) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BoostQuery) Areas(obj *Area, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *BoostQuery) AreasLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *BoostQuery) Genders(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *BoostQuery) GendersLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *BoostQuery) Interests(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *BoostQuery) InterestsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *BoostQuery) Lim() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BoostQuery) MutateLim(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func (rcv *BoostQuery) MaxAge() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BoostQuery) MutateMaxAge(n byte) bool {
	return rcv._tab.MutateByteSlot(12, n)
}

func (rcv *BoostQuery) MinAge() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BoostQuery) MutateMinAge(n byte) bool {
	return rcv._tab.MutateByteSlot(14, n)
}

func (rcv *BoostQuery) Countries(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *BoostQuery) CountriesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func BoostQueryStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func BoostQueryAddAreas(builder *flatbuffers.Builder, areas flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(areas), 0)
}
func BoostQueryStartAreasVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func BoostQueryAddGenders(builder *flatbuffers.Builder, genders flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(genders), 0)
}
func BoostQueryStartGendersVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func BoostQueryAddInterests(builder *flatbuffers.Builder, interests flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(interests), 0)
}
func BoostQueryStartInterestsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func BoostQueryAddLim(builder *flatbuffers.Builder, lim uint64) {
	builder.PrependUint64Slot(3, lim, 0)
}
func BoostQueryAddMaxAge(builder *flatbuffers.Builder, maxAge byte) {
	builder.PrependByteSlot(4, maxAge, 0)
}
func BoostQueryAddMinAge(builder *flatbuffers.Builder, minAge byte) {
	builder.PrependByteSlot(5, minAge, 0)
}
func BoostQueryAddCountries(builder *flatbuffers.Builder, countries flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(countries), 0)
}
func BoostQueryStartCountriesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func BoostQueryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
