// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BoostRequestT struct {
	SenderCreationCluster uint16 `json:"sender_creation_cluster"`
	DeviceId uint32 `json:"device_id"`
	SatsPerPerson uint32 `json:"sats_per_person"`
	Token string `json:"token"`
	SenderPublicKey []byte `json:"sender_public_key"`
	Query *BoostQueryT `json:"query"`
	MessageId []byte `json:"message_id"`
	PartialTxs []*PartialTxT `json:"partial_txs"`
	RequestTime int64 `json:"request_time"`
	SenderId uint64 `json:"sender_id"`
	InputSats uint64 `json:"input_sats"`
	FeeSats uint64 `json:"fee_sats"`
	FeeBytes uint64 `json:"fee_bytes"`
}

func (t *BoostRequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	tokenOffset := flatbuffers.UOffsetT(0)
	if t.Token != "" {
		tokenOffset = builder.CreateString(t.Token)
	}
	senderPublicKeyOffset := flatbuffers.UOffsetT(0)
	if t.SenderPublicKey != nil {
		senderPublicKeyOffset = builder.CreateByteString(t.SenderPublicKey)
	}
	queryOffset := t.Query.Pack(builder)
	messageIdOffset := flatbuffers.UOffsetT(0)
	if t.MessageId != nil {
		messageIdOffset = builder.CreateByteString(t.MessageId)
	}
	partialTxsOffset := flatbuffers.UOffsetT(0)
	if t.PartialTxs != nil {
		partialTxsLength := len(t.PartialTxs)
		partialTxsOffsets := make([]flatbuffers.UOffsetT, partialTxsLength)
		for j := 0; j < partialTxsLength; j++ {
			partialTxsOffsets[j] = t.PartialTxs[j].Pack(builder)
		}
		BoostRequestStartPartialTxsVector(builder, partialTxsLength)
		for j := partialTxsLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(partialTxsOffsets[j])
		}
		partialTxsOffset = builder.EndVector(partialTxsLength)
	}
	BoostRequestStart(builder)
	BoostRequestAddSenderCreationCluster(builder, t.SenderCreationCluster)
	BoostRequestAddDeviceId(builder, t.DeviceId)
	BoostRequestAddSatsPerPerson(builder, t.SatsPerPerson)
	BoostRequestAddToken(builder, tokenOffset)
	BoostRequestAddSenderPublicKey(builder, senderPublicKeyOffset)
	BoostRequestAddQuery(builder, queryOffset)
	BoostRequestAddMessageId(builder, messageIdOffset)
	BoostRequestAddPartialTxs(builder, partialTxsOffset)
	BoostRequestAddRequestTime(builder, t.RequestTime)
	BoostRequestAddSenderId(builder, t.SenderId)
	BoostRequestAddInputSats(builder, t.InputSats)
	BoostRequestAddFeeSats(builder, t.FeeSats)
	BoostRequestAddFeeBytes(builder, t.FeeBytes)
	return BoostRequestEnd(builder)
}

func (rcv *BoostRequest) UnPackTo(t *BoostRequestT) {
	t.SenderCreationCluster = rcv.SenderCreationCluster()
	t.DeviceId = rcv.DeviceId()
	t.SatsPerPerson = rcv.SatsPerPerson()
	t.Token = string(rcv.Token())
	t.SenderPublicKey = rcv.SenderPublicKeyBytes()
	t.Query = rcv.Query(nil).UnPack()
	t.MessageId = rcv.MessageIdBytes()
	partialTxsLength := rcv.PartialTxsLength()
	t.PartialTxs = make([]*PartialTxT, partialTxsLength)
	for j := 0; j < partialTxsLength; j++ {
		x := PartialTx{}
		rcv.PartialTxs(&x, j)
		t.PartialTxs[j] = x.UnPack()
	}
	t.RequestTime = rcv.RequestTime()
	t.SenderId = rcv.SenderId()
	t.InputSats = rcv.InputSats()
	t.FeeSats = rcv.FeeSats()
	t.FeeBytes = rcv.FeeBytes()
}

func (rcv *BoostRequest) UnPack() *BoostRequestT {
	if rcv == nil {
		return nil
	}
	t := &BoostRequestT{}
	rcv.UnPackTo(t)
	return t
}

type BoostRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsBoostRequest(buf []byte, offset flatbuffers.UOffsetT) *BoostRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BoostRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishBoostRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsBoostRequest(buf []byte, offset flatbuffers.UOffsetT) *BoostRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BoostRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBoostRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *BoostRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BoostRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BoostRequest) SenderCreationCluster() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BoostRequest) MutateSenderCreationCluster(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func (rcv *BoostRequest) DeviceId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BoostRequest) MutateDeviceId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *BoostRequest) SatsPerPerson() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BoostRequest) MutateSatsPerPerson(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func (rcv *BoostRequest) Token() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BoostRequest) SenderPublicKey(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *BoostRequest) SenderPublicKeyLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *BoostRequest) SenderPublicKeyBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BoostRequest) MutateSenderPublicKey(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *BoostRequest) Query(obj *BoostQuery) *BoostQuery {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(BoostQuery)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *BoostRequest) MessageId(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *BoostRequest) MessageIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *BoostRequest) MessageIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BoostRequest) MutateMessageId(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *BoostRequest) PartialTxs(obj *PartialTx, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *BoostRequest) PartialTxsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *BoostRequest) RequestTime() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BoostRequest) MutateRequestTime(n int64) bool {
	return rcv._tab.MutateInt64Slot(20, n)
}

func (rcv *BoostRequest) SenderId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BoostRequest) MutateSenderId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(22, n)
}

func (rcv *BoostRequest) InputSats() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BoostRequest) MutateInputSats(n uint64) bool {
	return rcv._tab.MutateUint64Slot(24, n)
}

func (rcv *BoostRequest) FeeSats() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BoostRequest) MutateFeeSats(n uint64) bool {
	return rcv._tab.MutateUint64Slot(26, n)
}

func (rcv *BoostRequest) FeeBytes() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BoostRequest) MutateFeeBytes(n uint64) bool {
	return rcv._tab.MutateUint64Slot(28, n)
}

func BoostRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(13)
}
func BoostRequestAddSenderCreationCluster(builder *flatbuffers.Builder, senderCreationCluster uint16) {
	builder.PrependUint16Slot(0, senderCreationCluster, 0)
}
func BoostRequestAddDeviceId(builder *flatbuffers.Builder, deviceId uint32) {
	builder.PrependUint32Slot(1, deviceId, 0)
}
func BoostRequestAddSatsPerPerson(builder *flatbuffers.Builder, satsPerPerson uint32) {
	builder.PrependUint32Slot(2, satsPerPerson, 0)
}
func BoostRequestAddToken(builder *flatbuffers.Builder, token flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(token), 0)
}
func BoostRequestAddSenderPublicKey(builder *flatbuffers.Builder, senderPublicKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(senderPublicKey), 0)
}
func BoostRequestStartSenderPublicKeyVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func BoostRequestAddQuery(builder *flatbuffers.Builder, query flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(query), 0)
}
func BoostRequestAddMessageId(builder *flatbuffers.Builder, messageId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(messageId), 0)
}
func BoostRequestStartMessageIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func BoostRequestAddPartialTxs(builder *flatbuffers.Builder, partialTxs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(partialTxs), 0)
}
func BoostRequestStartPartialTxsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func BoostRequestAddRequestTime(builder *flatbuffers.Builder, requestTime int64) {
	builder.PrependInt64Slot(8, requestTime, 0)
}
func BoostRequestAddSenderId(builder *flatbuffers.Builder, senderId uint64) {
	builder.PrependUint64Slot(9, senderId, 0)
}
func BoostRequestAddInputSats(builder *flatbuffers.Builder, inputSats uint64) {
	builder.PrependUint64Slot(10, inputSats, 0)
}
func BoostRequestAddFeeSats(builder *flatbuffers.Builder, feeSats uint64) {
	builder.PrependUint64Slot(11, feeSats, 0)
}
func BoostRequestAddFeeBytes(builder *flatbuffers.Builder, feeBytes uint64) {
	builder.PrependUint64Slot(12, feeBytes, 0)
}
func BoostRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
