// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BoostRequest2T struct {
	JobId string `json:"job_id"`
	RequestClusterName string `json:"request_cluster_name"`
	RequestTime int64 `json:"request_time"`
	Token string `json:"token"`
	DeviceId uint32 `json:"device_id"`
	SenderId uint64 `json:"sender_id"`
	SenderPublicKey []byte `json:"sender_public_key"`
	SenderCreationCluster uint16 `json:"sender_creation_cluster"`
	SatsPerPerson uint32 `json:"sats_per_person"`
	Query *BoostQueryT `json:"query"`
	MessageId []byte `json:"message_id"`
	InputSats uint64 `json:"input_sats"`
	FeeSats uint64 `json:"fee_sats"`
	FeeBytes uint64 `json:"fee_bytes"`
	PartialTxs []*PartialTxT `json:"partial_txs"`
}

func (t *BoostRequest2T) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	jobIdOffset := flatbuffers.UOffsetT(0)
	if t.JobId != "" {
		jobIdOffset = builder.CreateString(t.JobId)
	}
	requestClusterNameOffset := flatbuffers.UOffsetT(0)
	if t.RequestClusterName != "" {
		requestClusterNameOffset = builder.CreateString(t.RequestClusterName)
	}
	tokenOffset := flatbuffers.UOffsetT(0)
	if t.Token != "" {
		tokenOffset = builder.CreateString(t.Token)
	}
	senderPublicKeyOffset := flatbuffers.UOffsetT(0)
	if t.SenderPublicKey != nil {
		senderPublicKeyOffset = builder.CreateByteString(t.SenderPublicKey)
	}
	queryOffset := t.Query.Pack(builder)
	messageIdOffset := flatbuffers.UOffsetT(0)
	if t.MessageId != nil {
		messageIdOffset = builder.CreateByteString(t.MessageId)
	}
	partialTxsOffset := flatbuffers.UOffsetT(0)
	if t.PartialTxs != nil {
		partialTxsLength := len(t.PartialTxs)
		partialTxsOffsets := make([]flatbuffers.UOffsetT, partialTxsLength)
		for j := 0; j < partialTxsLength; j++ {
			partialTxsOffsets[j] = t.PartialTxs[j].Pack(builder)
		}
		BoostRequest2StartPartialTxsVector(builder, partialTxsLength)
		for j := partialTxsLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(partialTxsOffsets[j])
		}
		partialTxsOffset = builder.EndVector(partialTxsLength)
	}
	BoostRequest2Start(builder)
	BoostRequest2AddJobId(builder, jobIdOffset)
	BoostRequest2AddRequestClusterName(builder, requestClusterNameOffset)
	BoostRequest2AddRequestTime(builder, t.RequestTime)
	BoostRequest2AddToken(builder, tokenOffset)
	BoostRequest2AddDeviceId(builder, t.DeviceId)
	BoostRequest2AddSenderId(builder, t.SenderId)
	BoostRequest2AddSenderPublicKey(builder, senderPublicKeyOffset)
	BoostRequest2AddSenderCreationCluster(builder, t.SenderCreationCluster)
	BoostRequest2AddSatsPerPerson(builder, t.SatsPerPerson)
	BoostRequest2AddQuery(builder, queryOffset)
	BoostRequest2AddMessageId(builder, messageIdOffset)
	BoostRequest2AddInputSats(builder, t.InputSats)
	BoostRequest2AddFeeSats(builder, t.FeeSats)
	BoostRequest2AddFeeBytes(builder, t.FeeBytes)
	BoostRequest2AddPartialTxs(builder, partialTxsOffset)
	return BoostRequest2End(builder)
}

func (rcv *BoostRequest2) UnPackTo(t *BoostRequest2T) {
	t.JobId = string(rcv.JobId())
	t.RequestClusterName = string(rcv.RequestClusterName())
	t.RequestTime = rcv.RequestTime()
	t.Token = string(rcv.Token())
	t.DeviceId = rcv.DeviceId()
	t.SenderId = rcv.SenderId()
	t.SenderPublicKey = rcv.SenderPublicKeyBytes()
	t.SenderCreationCluster = rcv.SenderCreationCluster()
	t.SatsPerPerson = rcv.SatsPerPerson()
	t.Query = rcv.Query(nil).UnPack()
	t.MessageId = rcv.MessageIdBytes()
	t.InputSats = rcv.InputSats()
	t.FeeSats = rcv.FeeSats()
	t.FeeBytes = rcv.FeeBytes()
	partialTxsLength := rcv.PartialTxsLength()
	t.PartialTxs = make([]*PartialTxT, partialTxsLength)
	for j := 0; j < partialTxsLength; j++ {
		x := PartialTx{}
		rcv.PartialTxs(&x, j)
		t.PartialTxs[j] = x.UnPack()
	}
}

func (rcv *BoostRequest2) UnPack() *BoostRequest2T {
	if rcv == nil {
		return nil
	}
	t := &BoostRequest2T{}
	rcv.UnPackTo(t)
	return t
}

type BoostRequest2 struct {
	_tab flatbuffers.Table
}

func GetRootAsBoostRequest2(buf []byte, offset flatbuffers.UOffsetT) *BoostRequest2 {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BoostRequest2{}
	x.Init(buf, n+offset)
	return x
}

func FinishBoostRequest2Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsBoostRequest2(buf []byte, offset flatbuffers.UOffsetT) *BoostRequest2 {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BoostRequest2{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBoostRequest2Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *BoostRequest2) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BoostRequest2) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BoostRequest2) JobId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BoostRequest2) RequestClusterName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BoostRequest2) RequestTime() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BoostRequest2) MutateRequestTime(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func (rcv *BoostRequest2) Token() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BoostRequest2) DeviceId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BoostRequest2) MutateDeviceId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(12, n)
}

func (rcv *BoostRequest2) SenderId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BoostRequest2) MutateSenderId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(14, n)
}

func (rcv *BoostRequest2) SenderPublicKey(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *BoostRequest2) SenderPublicKeyLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *BoostRequest2) SenderPublicKeyBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BoostRequest2) MutateSenderPublicKey(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *BoostRequest2) SenderCreationCluster() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BoostRequest2) MutateSenderCreationCluster(n uint16) bool {
	return rcv._tab.MutateUint16Slot(18, n)
}

func (rcv *BoostRequest2) SatsPerPerson() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BoostRequest2) MutateSatsPerPerson(n uint32) bool {
	return rcv._tab.MutateUint32Slot(20, n)
}

func (rcv *BoostRequest2) Query(obj *BoostQuery) *BoostQuery {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(BoostQuery)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *BoostRequest2) MessageId(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *BoostRequest2) MessageIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *BoostRequest2) MessageIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BoostRequest2) MutateMessageId(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *BoostRequest2) InputSats() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BoostRequest2) MutateInputSats(n uint64) bool {
	return rcv._tab.MutateUint64Slot(26, n)
}

func (rcv *BoostRequest2) FeeSats() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BoostRequest2) MutateFeeSats(n uint64) bool {
	return rcv._tab.MutateUint64Slot(28, n)
}

func (rcv *BoostRequest2) FeeBytes() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BoostRequest2) MutateFeeBytes(n uint64) bool {
	return rcv._tab.MutateUint64Slot(30, n)
}

func (rcv *BoostRequest2) PartialTxs(obj *PartialTx, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *BoostRequest2) PartialTxsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func BoostRequest2Start(builder *flatbuffers.Builder) {
	builder.StartObject(15)
}
func BoostRequest2AddJobId(builder *flatbuffers.Builder, jobId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(jobId), 0)
}
func BoostRequest2AddRequestClusterName(builder *flatbuffers.Builder, requestClusterName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(requestClusterName), 0)
}
func BoostRequest2AddRequestTime(builder *flatbuffers.Builder, requestTime int64) {
	builder.PrependInt64Slot(2, requestTime, 0)
}
func BoostRequest2AddToken(builder *flatbuffers.Builder, token flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(token), 0)
}
func BoostRequest2AddDeviceId(builder *flatbuffers.Builder, deviceId uint32) {
	builder.PrependUint32Slot(4, deviceId, 0)
}
func BoostRequest2AddSenderId(builder *flatbuffers.Builder, senderId uint64) {
	builder.PrependUint64Slot(5, senderId, 0)
}
func BoostRequest2AddSenderPublicKey(builder *flatbuffers.Builder, senderPublicKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(senderPublicKey), 0)
}
func BoostRequest2StartSenderPublicKeyVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func BoostRequest2AddSenderCreationCluster(builder *flatbuffers.Builder, senderCreationCluster uint16) {
	builder.PrependUint16Slot(7, senderCreationCluster, 0)
}
func BoostRequest2AddSatsPerPerson(builder *flatbuffers.Builder, satsPerPerson uint32) {
	builder.PrependUint32Slot(8, satsPerPerson, 0)
}
func BoostRequest2AddQuery(builder *flatbuffers.Builder, query flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(query), 0)
}
func BoostRequest2AddMessageId(builder *flatbuffers.Builder, messageId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(10, flatbuffers.UOffsetT(messageId), 0)
}
func BoostRequest2StartMessageIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func BoostRequest2AddInputSats(builder *flatbuffers.Builder, inputSats uint64) {
	builder.PrependUint64Slot(11, inputSats, 0)
}
func BoostRequest2AddFeeSats(builder *flatbuffers.Builder, feeSats uint64) {
	builder.PrependUint64Slot(12, feeSats, 0)
}
func BoostRequest2AddFeeBytes(builder *flatbuffers.Builder, feeBytes uint64) {
	builder.PrependUint64Slot(13, feeBytes, 0)
}
func BoostRequest2AddPartialTxs(builder *flatbuffers.Builder, partialTxs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(14, flatbuffers.UOffsetT(partialTxs), 0)
}
func BoostRequest2StartPartialTxsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func BoostRequest2End(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
