// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BoosterT struct {
	Sats uint32 `json:"sats"`
	UtxoIx uint32 `json:"utxo_ix"`
	Txid []byte `json:"txid"`
	Secret []byte `json:"secret"`
	Interests []string `json:"interests"`
	MsgId []byte `json:"msg_id"`
	Timestamp int64 `json:"timestamp"`
	SenderId uint64 `json:"sender_id"`
	ReceiverId uint64 `json:"receiver_id"`
	Nonce uint64 `json:"nonce"`
}

func (t *BoosterT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	txidOffset := flatbuffers.UOffsetT(0)
	if t.Txid != nil {
		txidOffset = builder.CreateByteString(t.Txid)
	}
	secretOffset := flatbuffers.UOffsetT(0)
	if t.Secret != nil {
		secretOffset = builder.CreateByteString(t.Secret)
	}
	interestsOffset := flatbuffers.UOffsetT(0)
	if t.Interests != nil {
		interestsLength := len(t.Interests)
		interestsOffsets := make([]flatbuffers.UOffsetT, interestsLength)
		for j := 0; j < interestsLength; j++ {
			interestsOffsets[j] = builder.CreateString(t.Interests[j])
		}
		BoosterStartInterestsVector(builder, interestsLength)
		for j := interestsLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(interestsOffsets[j])
		}
		interestsOffset = builder.EndVector(interestsLength)
	}
	msgIdOffset := flatbuffers.UOffsetT(0)
	if t.MsgId != nil {
		msgIdOffset = builder.CreateByteString(t.MsgId)
	}
	BoosterStart(builder)
	BoosterAddSats(builder, t.Sats)
	BoosterAddUtxoIx(builder, t.UtxoIx)
	BoosterAddTxid(builder, txidOffset)
	BoosterAddSecret(builder, secretOffset)
	BoosterAddInterests(builder, interestsOffset)
	BoosterAddMsgId(builder, msgIdOffset)
	BoosterAddTimestamp(builder, t.Timestamp)
	BoosterAddSenderId(builder, t.SenderId)
	BoosterAddReceiverId(builder, t.ReceiverId)
	BoosterAddNonce(builder, t.Nonce)
	return BoosterEnd(builder)
}

func (rcv *Booster) UnPackTo(t *BoosterT) {
	t.Sats = rcv.Sats()
	t.UtxoIx = rcv.UtxoIx()
	t.Txid = rcv.TxidBytes()
	t.Secret = rcv.SecretBytes()
	interestsLength := rcv.InterestsLength()
	t.Interests = make([]string, interestsLength)
	for j := 0; j < interestsLength; j++ {
		t.Interests[j] = string(rcv.Interests(j))
	}
	t.MsgId = rcv.MsgIdBytes()
	t.Timestamp = rcv.Timestamp()
	t.SenderId = rcv.SenderId()
	t.ReceiverId = rcv.ReceiverId()
	t.Nonce = rcv.Nonce()
}

func (rcv *Booster) UnPack() *BoosterT {
	if rcv == nil {
		return nil
	}
	t := &BoosterT{}
	rcv.UnPackTo(t)
	return t
}

type Booster struct {
	_tab flatbuffers.Table
}

func GetRootAsBooster(buf []byte, offset flatbuffers.UOffsetT) *Booster {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Booster{}
	x.Init(buf, n+offset)
	return x
}

func FinishBoosterBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsBooster(buf []byte, offset flatbuffers.UOffsetT) *Booster {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Booster{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBoosterBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Booster) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Booster) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Booster) Sats() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Booster) MutateSats(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *Booster) UtxoIx() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Booster) MutateUtxoIx(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *Booster) Txid(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *Booster) TxidLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Booster) TxidBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Booster) MutateTxid(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *Booster) Secret(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *Booster) SecretLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Booster) SecretBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Booster) MutateSecret(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *Booster) Interests(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *Booster) InterestsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Booster) MsgId(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *Booster) MsgIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Booster) MsgIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Booster) MutateMsgId(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *Booster) Timestamp() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Booster) MutateTimestamp(n int64) bool {
	return rcv._tab.MutateInt64Slot(16, n)
}

func (rcv *Booster) SenderId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Booster) MutateSenderId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(18, n)
}

func (rcv *Booster) ReceiverId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Booster) MutateReceiverId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(20, n)
}

func (rcv *Booster) Nonce() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Booster) MutateNonce(n uint64) bool {
	return rcv._tab.MutateUint64Slot(22, n)
}

func BoosterStart(builder *flatbuffers.Builder) {
	builder.StartObject(10)
}
func BoosterAddSats(builder *flatbuffers.Builder, sats uint32) {
	builder.PrependUint32Slot(0, sats, 0)
}
func BoosterAddUtxoIx(builder *flatbuffers.Builder, utxoIx uint32) {
	builder.PrependUint32Slot(1, utxoIx, 0)
}
func BoosterAddTxid(builder *flatbuffers.Builder, txid flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(txid), 0)
}
func BoosterStartTxidVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func BoosterAddSecret(builder *flatbuffers.Builder, secret flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(secret), 0)
}
func BoosterStartSecretVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func BoosterAddInterests(builder *flatbuffers.Builder, interests flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(interests), 0)
}
func BoosterStartInterestsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func BoosterAddMsgId(builder *flatbuffers.Builder, msgId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(msgId), 0)
}
func BoosterStartMsgIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func BoosterAddTimestamp(builder *flatbuffers.Builder, timestamp int64) {
	builder.PrependInt64Slot(6, timestamp, 0)
}
func BoosterAddSenderId(builder *flatbuffers.Builder, senderId uint64) {
	builder.PrependUint64Slot(7, senderId, 0)
}
func BoosterAddReceiverId(builder *flatbuffers.Builder, receiverId uint64) {
	builder.PrependUint64Slot(8, receiverId, 0)
}
func BoosterAddNonce(builder *flatbuffers.Builder, nonce uint64) {
	builder.PrependUint64Slot(9, nonce, 0)
}
func BoosterEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
