// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import "strconv"

type Command byte

const (
	CommandChatEvent                 Command = 0
	CommandMessageSent               Command = 1
	CommandScrollRequest             Command = 2
	CommandNotifications             Command = 3
	CommandChatScrollDone            Command = 4
	CommandChatConnReq               Command = 5
	CommandChatDiscReq               Command = 6
	CommandChatEventFromScroll       Command = 7
	CommandPublishChatError          Command = 8
	CommandNewGroup                  Command = 9
	CommandNewGroupErr               Command = 10
	CommandNewGroupSuccess           Command = 11
	CommandConnectionError           Command = 12
	CommandConnectionConfirmation    Command = 13
	CommandDisconnectionConfirmation Command = 14
)

var EnumNamesCommand = map[Command]string{
	CommandChatEvent:                 "ChatEvent",
	CommandMessageSent:               "MessageSent",
	CommandScrollRequest:             "ScrollRequest",
	CommandNotifications:             "Notifications",
	CommandChatScrollDone:            "ChatScrollDone",
	CommandChatConnReq:               "ChatConnReq",
	CommandChatDiscReq:               "ChatDiscReq",
	CommandChatEventFromScroll:       "ChatEventFromScroll",
	CommandPublishChatError:          "PublishChatError",
	CommandNewGroup:                  "NewGroup",
	CommandNewGroupErr:               "NewGroupErr",
	CommandNewGroupSuccess:           "NewGroupSuccess",
	CommandConnectionError:           "ConnectionError",
	CommandConnectionConfirmation:    "ConnectionConfirmation",
	CommandDisconnectionConfirmation: "DisconnectionConfirmation",
}

var EnumValuesCommand = map[string]Command{
	"ChatEvent":                 CommandChatEvent,
	"MessageSent":               CommandMessageSent,
	"ScrollRequest":             CommandScrollRequest,
	"Notifications":             CommandNotifications,
	"ChatScrollDone":            CommandChatScrollDone,
	"ChatConnReq":               CommandChatConnReq,
	"ChatDiscReq":               CommandChatDiscReq,
	"ChatEventFromScroll":       CommandChatEventFromScroll,
	"PublishChatError":          CommandPublishChatError,
	"NewGroup":                  CommandNewGroup,
	"NewGroupErr":               CommandNewGroupErr,
	"NewGroupSuccess":           CommandNewGroupSuccess,
	"ConnectionError":           CommandConnectionError,
	"ConnectionConfirmation":    CommandConnectionConfirmation,
	"DisconnectionConfirmation": CommandDisconnectionConfirmation,
}

func (v Command) String() string {
	if s, ok := EnumNamesCommand[v]; ok {
		return s
	}
	return "Command(" + strconv.FormatInt(int64(v), 10) + ")"
}
