// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import "strconv"

type DatumIdentifier byte

const (
	DatumIdentifierIsMore DatumIdentifier = 0
	DatumIdentifierData   DatumIdentifier = 1
)

var EnumNamesDatumIdentifier = map[DatumIdentifier]string{
	DatumIdentifierIsMore: "IsMore",
	DatumIdentifierData:   "Data",
}

var EnumValuesDatumIdentifier = map[string]DatumIdentifier{
	"IsMore": DatumIdentifierIsMore,
	"Data":   DatumIdentifierData,
}

func (v DatumIdentifier) String() string {
	if s, ok := EnumNamesDatumIdentifier[v]; ok {
		return s
	}
	return "DatumIdentifier(" + strconv.FormatInt(int64(v), 10) + ")"
}
