// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FullSticker struct {
	_tab flatbuffers.Table
}

func GetRootAsFullSticker(buf []byte, offset flatbuffers.UOffsetT) *FullSticker {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FullSticker{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsFullSticker(buf []byte, offset flatbuffers.UOffsetT) *FullSticker {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FullSticker{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *FullSticker) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FullSticker) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FullSticker) Sticker(obj *Sticker) *Sticker {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Sticker)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *FullSticker) FullMedia(obj *FullMedia) *FullMedia {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(FullMedia)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func FullStickerStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func FullStickerAddSticker(builder *flatbuffers.Builder, sticker flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(sticker), 0)
}
func FullStickerAddFullMedia(builder *flatbuffers.Builder, fullMedia flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(fullMedia), 0)
}
func FullStickerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
