// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import "strconv"

type IdKind byte

const (
	IdKindMessage  IdKind = 0
	IdKindRoom     IdKind = 1
	IdKindMedia    IdKind = 2
	IdKindMediaRef IdKind = 3
	IdKindTxRef    IdKind = 4
	IdKindPush     IdKind = 5
	IdKindSnip     IdKind = 6
	IdKindIddev    IdKind = 7
	IdKindSticker  IdKind = 8
	IdKindBoost    IdKind = 9
)

var EnumNamesIdKind = map[IdKind]string{
	IdKindMessage:  "Message",
	IdKindRoom:     "Room",
	IdKindMedia:    "Media",
	IdKindMediaRef: "MediaRef",
	IdKindTxRef:    "TxRef",
	IdKindPush:     "Push",
	IdKindSnip:     "Snip",
	IdKindIddev:    "Iddev",
	IdKindSticker:  "Sticker",
	IdKindBoost:    "Boost",
}

var EnumValuesIdKind = map[string]IdKind{
	"Message":  IdKindMessage,
	"Room":     IdKindRoom,
	"Media":    IdKindMedia,
	"MediaRef": IdKindMediaRef,
	"TxRef":    IdKindTxRef,
	"Push":     IdKindPush,
	"Snip":     IdKindSnip,
	"Iddev":    IdKindIddev,
	"Sticker":  IdKindSticker,
	"Boost":    IdKindBoost,
}

func (v IdKind) String() string {
	if s, ok := EnumNamesIdKind[v]; ok {
		return s
	}
	return "IdKind(" + strconv.FormatInt(int64(v), 10) + ")"
}
