// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import "strconv"

type IdKind byte

const (
	IdKindMessage      IdKind = 0
	IdKindRoom         IdKind = 1
	IdKindMedia        IdKind = 2
	IdKindMediaRef     IdKind = 3
	IdKindIddev        IdKind = 4
	IdKindBoost        IdKind = 5
	IdKindPaymentRef   IdKind = 6
	IdKindPayment      IdKind = 7
	IdKindTxout        IdKind = 8
	IdKindTxin         IdKind = 9
	IdKindStatic       IdKind = 10
	IdKindTxid         IdKind = 11
	IdKindHex          IdKind = 12
	IdKindTimestamp    IdKind = 13
	IdKindVersionstamp IdKind = 14
	IdKindStrings      IdKind = 15
	IdKindThumbnail    IdKind = 16
	IdKindAccess       IdKind = 17
	IdKindFunding      IdKind = 18
	IdKindBoosting     IdKind = 19
	IdKindNaivePayment IdKind = 20
)

var EnumNamesIdKind = map[IdKind]string{
	IdKindMessage:      "Message",
	IdKindRoom:         "Room",
	IdKindMedia:        "Media",
	IdKindMediaRef:     "MediaRef",
	IdKindIddev:        "Iddev",
	IdKindBoost:        "Boost",
	IdKindPaymentRef:   "PaymentRef",
	IdKindPayment:      "Payment",
	IdKindTxout:        "Txout",
	IdKindTxin:         "Txin",
	IdKindStatic:       "Static",
	IdKindTxid:         "Txid",
	IdKindHex:          "Hex",
	IdKindTimestamp:    "Timestamp",
	IdKindVersionstamp: "Versionstamp",
	IdKindStrings:      "Strings",
	IdKindThumbnail:    "Thumbnail",
	IdKindAccess:       "Access",
	IdKindFunding:      "Funding",
	IdKindBoosting:     "Boosting",
	IdKindNaivePayment: "NaivePayment",
}

var EnumValuesIdKind = map[string]IdKind{
	"Message":      IdKindMessage,
	"Room":         IdKindRoom,
	"Media":        IdKindMedia,
	"MediaRef":     IdKindMediaRef,
	"Iddev":        IdKindIddev,
	"Boost":        IdKindBoost,
	"PaymentRef":   IdKindPaymentRef,
	"Payment":      IdKindPayment,
	"Txout":        IdKindTxout,
	"Txin":         IdKindTxin,
	"Static":       IdKindStatic,
	"Txid":         IdKindTxid,
	"Hex":          IdKindHex,
	"Timestamp":    IdKindTimestamp,
	"Versionstamp": IdKindVersionstamp,
	"Strings":      IdKindStrings,
	"Thumbnail":    IdKindThumbnail,
	"Access":       IdKindAccess,
	"Funding":      IdKindFunding,
	"Boosting":     IdKindBoosting,
	"NaivePayment": IdKindNaivePayment,
}

func (v IdKind) String() string {
	if s, ok := EnumNamesIdKind[v]; ok {
		return s
	}
	return "IdKind(" + strconv.FormatInt(int64(v), 10) + ")"
}
