// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import "strconv"

type IdKind byte

const (
	IdKindMessage      IdKind = 0
	IdKindMessage2     IdKind = 1
	IdKindRoom         IdKind = 2
	IdKindRoom2        IdKind = 3
	IdKindMedia        IdKind = 4
	IdKindMediaRef     IdKind = 5
	IdKindIddev        IdKind = 6
	IdKindSticker      IdKind = 7
	IdKindBoost        IdKind = 8
	IdKindPaymentRef   IdKind = 9
	IdKindPayment      IdKind = 10
	IdKindTxout        IdKind = 11
	IdKindTxin         IdKind = 12
	IdKindStatic       IdKind = 13
	IdKindTxid         IdKind = 14
	IdKindHex          IdKind = 15
	IdKindTimestamp    IdKind = 16
	IdKindVersionstamp IdKind = 17
	IdKindStrings      IdKind = 18
)

var EnumNamesIdKind = map[IdKind]string{
	IdKindMessage:      "Message",
	IdKindMessage2:     "Message2",
	IdKindRoom:         "Room",
	IdKindRoom2:        "Room2",
	IdKindMedia:        "Media",
	IdKindMediaRef:     "MediaRef",
	IdKindIddev:        "Iddev",
	IdKindSticker:      "Sticker",
	IdKindBoost:        "Boost",
	IdKindPaymentRef:   "PaymentRef",
	IdKindPayment:      "Payment",
	IdKindTxout:        "Txout",
	IdKindTxin:         "Txin",
	IdKindStatic:       "Static",
	IdKindTxid:         "Txid",
	IdKindHex:          "Hex",
	IdKindTimestamp:    "Timestamp",
	IdKindVersionstamp: "Versionstamp",
	IdKindStrings:      "Strings",
}

var EnumValuesIdKind = map[string]IdKind{
	"Message":      IdKindMessage,
	"Message2":     IdKindMessage2,
	"Room":         IdKindRoom,
	"Room2":        IdKindRoom2,
	"Media":        IdKindMedia,
	"MediaRef":     IdKindMediaRef,
	"Iddev":        IdKindIddev,
	"Sticker":      IdKindSticker,
	"Boost":        IdKindBoost,
	"PaymentRef":   IdKindPaymentRef,
	"Payment":      IdKindPayment,
	"Txout":        IdKindTxout,
	"Txin":         IdKindTxin,
	"Static":       IdKindStatic,
	"Txid":         IdKindTxid,
	"Hex":          IdKindHex,
	"Timestamp":    IdKindTimestamp,
	"Versionstamp": IdKindVersionstamp,
	"Strings":      IdKindStrings,
}

func (v IdKind) String() string {
	if s, ok := EnumNamesIdKind[v]; ok {
		return s
	}
	return "IdKind(" + strconv.FormatInt(int64(v), 10) + ")"
}
