// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import "strconv"

type IdSize byte

const (
	IdSizeNodeId    IdSize = 8
	IdSizeTxVersion IdSize = 10
	IdSizeIddev     IdSize = 13
	IdSizeMediaId   IdSize = 19
	IdSizeRoom2     IdSize = 19
	IdSizeMediaRef  IdSize = 31
	IdSizeRoom      IdSize = 32
	IdSizeMsgId2    IdSize = 33
	IdSizeTxid      IdSize = 33
	IdSizeSticker   IdSize = 40
	IdSizeMsgId     IdSize = 46
)

var EnumNamesIdSize = map[IdSize]string{
	IdSizeNodeId:    "NodeId",
	IdSizeTxVersion: "TxVersion",
	IdSizeIddev:     "Iddev",
	IdSizeMediaId:   "MediaId",
	IdSizeRoom2:     "Room2",
	IdSizeMediaRef:  "MediaRef",
	IdSizeRoom:      "Room",
	IdSizeMsgId2:    "MsgId2",
	IdSizeTxid:      "Txid",
	IdSizeSticker:   "Sticker",
	IdSizeMsgId:     "MsgId",
}

var EnumValuesIdSize = map[string]IdSize{
	"NodeId":    IdSizeNodeId,
	"TxVersion": IdSizeTxVersion,
	"Iddev":     IdSizeIddev,
	"MediaId":   IdSizeMediaId,
	"Room2":     IdSizeRoom2,
	"MediaRef":  IdSizeMediaRef,
	"Room":      IdSizeRoom,
	"MsgId2":    IdSizeMsgId2,
	"Txid":      IdSizeTxid,
	"Sticker":   IdSizeSticker,
	"MsgId":     IdSizeMsgId,
}

func (v IdSize) String() string {
	if s, ok := EnumNamesIdSize[v]; ok {
		return s
	}
	return "IdSize(" + strconv.FormatInt(int64(v), 10) + ")"
}
