// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LatLonT struct {
	Lat float64 `json:"lat"`
	Lon float64 `json:"lon"`
	RefDist float64 `json:"ref_dist"`
}

func (t *LatLonT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	LatLonStart(builder)
	LatLonAddLat(builder, t.Lat)
	LatLonAddLon(builder, t.Lon)
	LatLonAddRefDist(builder, t.RefDist)
	return LatLonEnd(builder)
}

func (rcv *LatLon) UnPackTo(t *LatLonT) {
	t.Lat = rcv.Lat()
	t.Lon = rcv.Lon()
	t.RefDist = rcv.RefDist()
}

func (rcv *LatLon) UnPack() *LatLonT {
	if rcv == nil {
		return nil
	}
	t := &LatLonT{}
	rcv.UnPackTo(t)
	return t
}

type LatLon struct {
	_tab flatbuffers.Table
}

func GetRootAsLatLon(buf []byte, offset flatbuffers.UOffsetT) *LatLon {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LatLon{}
	x.Init(buf, n+offset)
	return x
}

func FinishLatLonBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsLatLon(buf []byte, offset flatbuffers.UOffsetT) *LatLon {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LatLon{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedLatLonBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *LatLon) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LatLon) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LatLon) Lat() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *LatLon) MutateLat(n float64) bool {
	return rcv._tab.MutateFloat64Slot(4, n)
}

func (rcv *LatLon) Lon() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *LatLon) MutateLon(n float64) bool {
	return rcv._tab.MutateFloat64Slot(6, n)
}

func (rcv *LatLon) RefDist() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *LatLon) MutateRefDist(n float64) bool {
	return rcv._tab.MutateFloat64Slot(8, n)
}

func LatLonStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func LatLonAddLat(builder *flatbuffers.Builder, lat float64) {
	builder.PrependFloat64Slot(0, lat, 0.0)
}
func LatLonAddLon(builder *flatbuffers.Builder, lon float64) {
	builder.PrependFloat64Slot(1, lon, 0.0)
}
func LatLonAddRefDist(builder *flatbuffers.Builder, refDist float64) {
	builder.PrependFloat64Slot(2, refDist, 0.0)
}
func LatLonEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
