// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MediaT struct {
	Id []int8 `json:"id"`
	IsReversed bool `json:"is_reversed"`
	IsEncrypted bool `json:"is_encrypted"`
	OwnerId *NodeIdT `json:"owner_id"`
	Timestamp int64 `json:"timestamp"`
}

func (t *MediaT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	idOffset := flatbuffers.UOffsetT(0)
	if t.Id != nil {
		idLength := len(t.Id)
		MediaStartIdVector(builder, idLength)
		for j := idLength - 1; j >= 0; j-- {
			builder.PrependInt8(t.Id[j])
		}
		idOffset = builder.EndVector(idLength)
	}
	ownerIdOffset := t.OwnerId.Pack(builder)
	MediaStart(builder)
	MediaAddId(builder, idOffset)
	MediaAddIsReversed(builder, t.IsReversed)
	MediaAddIsEncrypted(builder, t.IsEncrypted)
	MediaAddOwnerId(builder, ownerIdOffset)
	MediaAddTimestamp(builder, t.Timestamp)
	return MediaEnd(builder)
}

func (rcv *Media) UnPackTo(t *MediaT) {
	idLength := rcv.IdLength()
	t.Id = make([]int8, idLength)
	for j := 0; j < idLength; j++ {
		t.Id[j] = rcv.Id(j)
	}
	t.IsReversed = rcv.IsReversed()
	t.IsEncrypted = rcv.IsEncrypted()
	t.OwnerId = rcv.OwnerId(nil).UnPack()
	t.Timestamp = rcv.Timestamp()
}

func (rcv *Media) UnPack() *MediaT {
	if rcv == nil {
		return nil
	}
	t := &MediaT{}
	rcv.UnPackTo(t)
	return t
}

type Media struct {
	_tab flatbuffers.Table
}

func GetRootAsMedia(buf []byte, offset flatbuffers.UOffsetT) *Media {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Media{}
	x.Init(buf, n+offset)
	return x
}

func FinishMediaBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMedia(buf []byte, offset flatbuffers.UOffsetT) *Media {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Media{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMediaBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Media) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Media) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Media) Id(j int) int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt8(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *Media) IdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Media) MutateId(j int, n int8) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt8(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *Media) IsReversed() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *Media) MutateIsReversed(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *Media) IsEncrypted() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *Media) MutateIsEncrypted(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func (rcv *Media) OwnerId(obj *NodeId) *NodeId {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(NodeId)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Media) Timestamp() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Media) MutateTimestamp(n int64) bool {
	return rcv._tab.MutateInt64Slot(12, n)
}

func MediaStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func MediaAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func MediaStartIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func MediaAddIsReversed(builder *flatbuffers.Builder, isReversed bool) {
	builder.PrependBoolSlot(1, isReversed, false)
}
func MediaAddIsEncrypted(builder *flatbuffers.Builder, isEncrypted bool) {
	builder.PrependBoolSlot(2, isEncrypted, false)
}
func MediaAddOwnerId(builder *flatbuffers.Builder, ownerId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(ownerId), 0)
}
func MediaAddTimestamp(builder *flatbuffers.Builder, timestamp int64) {
	builder.PrependInt64Slot(4, timestamp, 0)
}
func MediaEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
