// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MediaReferenceT struct {
	Prefix IdKind `json:"prefix"`
	Timestamp int64 `json:"timestamp"`
	RawId []byte `json:"raw_id"`
	Cluster uint16 `json:"cluster"`
	Perm bool `json:"perm"`
}

func (t *MediaReferenceT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	rawIdOffset := flatbuffers.UOffsetT(0)
	if t.RawId != nil {
		rawIdOffset = builder.CreateByteString(t.RawId)
	}
	MediaReferenceStart(builder)
	MediaReferenceAddPrefix(builder, t.Prefix)
	MediaReferenceAddTimestamp(builder, t.Timestamp)
	MediaReferenceAddRawId(builder, rawIdOffset)
	MediaReferenceAddCluster(builder, t.Cluster)
	MediaReferenceAddPerm(builder, t.Perm)
	return MediaReferenceEnd(builder)
}

func (rcv *MediaReference) UnPackTo(t *MediaReferenceT) {
	t.Prefix = rcv.Prefix()
	t.Timestamp = rcv.Timestamp()
	t.RawId = rcv.RawIdBytes()
	t.Cluster = rcv.Cluster()
	t.Perm = rcv.Perm()
}

func (rcv *MediaReference) UnPack() *MediaReferenceT {
	if rcv == nil {
		return nil
	}
	t := &MediaReferenceT{}
	rcv.UnPackTo(t)
	return t
}

type MediaReference struct {
	_tab flatbuffers.Table
}

func GetRootAsMediaReference(buf []byte, offset flatbuffers.UOffsetT) *MediaReference {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MediaReference{}
	x.Init(buf, n+offset)
	return x
}

func FinishMediaReferenceBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMediaReference(buf []byte, offset flatbuffers.UOffsetT) *MediaReference {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MediaReference{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMediaReferenceBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MediaReference) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MediaReference) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MediaReference) Prefix() IdKind {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return IdKind(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *MediaReference) MutatePrefix(n IdKind) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *MediaReference) Timestamp() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MediaReference) MutateTimestamp(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *MediaReference) RawId(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *MediaReference) RawIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MediaReference) RawIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MediaReference) MutateRawId(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *MediaReference) Cluster() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MediaReference) MutateCluster(n uint16) bool {
	return rcv._tab.MutateUint16Slot(10, n)
}

func (rcv *MediaReference) Perm() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *MediaReference) MutatePerm(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func MediaReferenceStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func MediaReferenceAddPrefix(builder *flatbuffers.Builder, prefix IdKind) {
	builder.PrependByteSlot(0, byte(prefix), 0)
}
func MediaReferenceAddTimestamp(builder *flatbuffers.Builder, timestamp int64) {
	builder.PrependInt64Slot(1, timestamp, 0)
}
func MediaReferenceAddRawId(builder *flatbuffers.Builder, rawId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(rawId), 0)
}
func MediaReferenceStartRawIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func MediaReferenceAddCluster(builder *flatbuffers.Builder, cluster uint16) {
	builder.PrependUint16Slot(3, cluster, 0)
}
func MediaReferenceAddPerm(builder *flatbuffers.Builder, perm bool) {
	builder.PrependBoolSlot(4, perm, false)
}
func MediaReferenceEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
