// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MediaMetadataT struct {
	Reference *MediaReferenceT `json:"reference"`
	Metadata []byte `json:"metadata"`
	HasData bool `json:"has_data"`
}

func (t *MediaMetadataT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	referenceOffset := t.Reference.Pack(builder)
	metadataOffset := flatbuffers.UOffsetT(0)
	if t.Metadata != nil {
		metadataOffset = builder.CreateByteString(t.Metadata)
	}
	MediaMetadataStart(builder)
	MediaMetadataAddReference(builder, referenceOffset)
	MediaMetadataAddMetadata(builder, metadataOffset)
	MediaMetadataAddHasData(builder, t.HasData)
	return MediaMetadataEnd(builder)
}

func (rcv *MediaMetadata) UnPackTo(t *MediaMetadataT) {
	t.Reference = rcv.Reference(nil).UnPack()
	t.Metadata = rcv.MetadataBytes()
	t.HasData = rcv.HasData()
}

func (rcv *MediaMetadata) UnPack() *MediaMetadataT {
	if rcv == nil {
		return nil
	}
	t := &MediaMetadataT{}
	rcv.UnPackTo(t)
	return t
}

type MediaMetadata struct {
	_tab flatbuffers.Table
}

func GetRootAsMediaMetadata(buf []byte, offset flatbuffers.UOffsetT) *MediaMetadata {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MediaMetadata{}
	x.Init(buf, n+offset)
	return x
}

func FinishMediaMetadataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMediaMetadata(buf []byte, offset flatbuffers.UOffsetT) *MediaMetadata {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MediaMetadata{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMediaMetadataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MediaMetadata) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MediaMetadata) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MediaMetadata) Reference(obj *MediaReference) *MediaReference {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(MediaReference)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *MediaMetadata) Metadata(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *MediaMetadata) MetadataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MediaMetadata) MetadataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MediaMetadata) MutateMetadata(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *MediaMetadata) HasData() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *MediaMetadata) MutateHasData(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func MediaMetadataStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func MediaMetadataAddReference(builder *flatbuffers.Builder, reference flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(reference), 0)
}
func MediaMetadataAddMetadata(builder *flatbuffers.Builder, metadata flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(metadata), 0)
}
func MediaMetadataStartMetadataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func MediaMetadataAddHasData(builder *flatbuffers.Builder, hasData bool) {
	builder.PrependBoolSlot(2, hasData, false)
}
func MediaMetadataEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
