// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MessageEvent2T struct {
	ChatId *MessageIdT `json:"chat_id"`
	Payload []byte `json:"payload"`
}

func (t *MessageEvent2T) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	chatIdOffset := t.ChatId.Pack(builder)
	payloadOffset := flatbuffers.UOffsetT(0)
	if t.Payload != nil {
		payloadOffset = builder.CreateByteString(t.Payload)
	}
	MessageEvent2Start(builder)
	MessageEvent2AddChatId(builder, chatIdOffset)
	MessageEvent2AddPayload(builder, payloadOffset)
	return MessageEvent2End(builder)
}

func (rcv *MessageEvent2) UnPackTo(t *MessageEvent2T) {
	t.ChatId = rcv.ChatId(nil).UnPack()
	t.Payload = rcv.PayloadBytes()
}

func (rcv *MessageEvent2) UnPack() *MessageEvent2T {
	if rcv == nil {
		return nil
	}
	t := &MessageEvent2T{}
	rcv.UnPackTo(t)
	return t
}

type MessageEvent2 struct {
	_tab flatbuffers.Table
}

func GetRootAsMessageEvent2(buf []byte, offset flatbuffers.UOffsetT) *MessageEvent2 {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MessageEvent2{}
	x.Init(buf, n+offset)
	return x
}

func FinishMessageEvent2Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMessageEvent2(buf []byte, offset flatbuffers.UOffsetT) *MessageEvent2 {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MessageEvent2{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMessageEvent2Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MessageEvent2) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MessageEvent2) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MessageEvent2) ChatId(obj *MessageId) *MessageId {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(MessageId)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *MessageEvent2) Payload(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *MessageEvent2) PayloadLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MessageEvent2) PayloadBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MessageEvent2) MutatePayload(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func MessageEvent2Start(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MessageEvent2AddChatId(builder *flatbuffers.Builder, chatId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(chatId), 0)
}
func MessageEvent2AddPayload(builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(payload), 0)
}
func MessageEvent2StartPayloadVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func MessageEvent2End(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
