// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import "strconv"

type MessageSuffix byte

const (
	MessageSuffixDefault     MessageSuffix = 0
	MessageSuffixUnsent      MessageSuffix = 1
	MessageSuffixChat        MessageSuffix = 2
	MessageSuffixSnip        MessageSuffix = 3
	MessageSuffixReaction    MessageSuffix = 4
	MessageSuffixIncrement   MessageSuffix = 5
	MessageSuffixPlaceholder MessageSuffix = 6
	MessageSuffixBoost       MessageSuffix = 7
)

var EnumNamesMessageSuffix = map[MessageSuffix]string{
	MessageSuffixDefault:     "Default",
	MessageSuffixUnsent:      "Unsent",
	MessageSuffixChat:        "Chat",
	MessageSuffixSnip:        "Snip",
	MessageSuffixReaction:    "Reaction",
	MessageSuffixIncrement:   "Increment",
	MessageSuffixPlaceholder: "Placeholder",
	MessageSuffixBoost:       "Boost",
}

var EnumValuesMessageSuffix = map[string]MessageSuffix{
	"Default":     MessageSuffixDefault,
	"Unsent":      MessageSuffixUnsent,
	"Chat":        MessageSuffixChat,
	"Snip":        MessageSuffixSnip,
	"Reaction":    MessageSuffixReaction,
	"Increment":   MessageSuffixIncrement,
	"Placeholder": MessageSuffixPlaceholder,
	"Boost":       MessageSuffixBoost,
}

func (v MessageSuffix) String() string {
	if s, ok := EnumNamesMessageSuffix[v]; ok {
		return s
	}
	return "MessageSuffix(" + strconv.FormatInt(int64(v), 10) + ")"
}
