// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MessageId2T struct {
	Prefix IdKind `json:"prefix"`
	Room *Room2T `json:"room"`
	TxVersion []byte `json:"tx_version"`
	UserVersion uint16 `json:"user_version"`
	Suffix MessageSuffix `json:"suffix"`
}

func (t *MessageId2T) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	roomOffset := t.Room.Pack(builder)
	txVersionOffset := flatbuffers.UOffsetT(0)
	if t.TxVersion != nil {
		txVersionOffset = builder.CreateByteString(t.TxVersion)
	}
	MessageId2Start(builder)
	MessageId2AddPrefix(builder, t.Prefix)
	MessageId2AddRoom(builder, roomOffset)
	MessageId2AddTxVersion(builder, txVersionOffset)
	MessageId2AddUserVersion(builder, t.UserVersion)
	MessageId2AddSuffix(builder, t.Suffix)
	return MessageId2End(builder)
}

func (rcv *MessageId2) UnPackTo(t *MessageId2T) {
	t.Prefix = rcv.Prefix()
	t.Room = rcv.Room(nil).UnPack()
	t.TxVersion = rcv.TxVersionBytes()
	t.UserVersion = rcv.UserVersion()
	t.Suffix = rcv.Suffix()
}

func (rcv *MessageId2) UnPack() *MessageId2T {
	if rcv == nil {
		return nil
	}
	t := &MessageId2T{}
	rcv.UnPackTo(t)
	return t
}

type MessageId2 struct {
	_tab flatbuffers.Table
}

func GetRootAsMessageId2(buf []byte, offset flatbuffers.UOffsetT) *MessageId2 {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MessageId2{}
	x.Init(buf, n+offset)
	return x
}

func FinishMessageId2Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMessageId2(buf []byte, offset flatbuffers.UOffsetT) *MessageId2 {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MessageId2{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMessageId2Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MessageId2) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MessageId2) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MessageId2) Prefix() IdKind {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return IdKind(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *MessageId2) MutatePrefix(n IdKind) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *MessageId2) Room(obj *Room2) *Room2 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Room2)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *MessageId2) TxVersion(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *MessageId2) TxVersionLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MessageId2) TxVersionBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MessageId2) MutateTxVersion(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *MessageId2) UserVersion() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MessageId2) MutateUserVersion(n uint16) bool {
	return rcv._tab.MutateUint16Slot(10, n)
}

func (rcv *MessageId2) Suffix() MessageSuffix {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return MessageSuffix(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *MessageId2) MutateSuffix(n MessageSuffix) bool {
	return rcv._tab.MutateByteSlot(12, byte(n))
}

func MessageId2Start(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func MessageId2AddPrefix(builder *flatbuffers.Builder, prefix IdKind) {
	builder.PrependByteSlot(0, byte(prefix), 0)
}
func MessageId2AddRoom(builder *flatbuffers.Builder, room flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(room), 0)
}
func MessageId2AddTxVersion(builder *flatbuffers.Builder, txVersion flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(txVersion), 0)
}
func MessageId2StartTxVersionVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func MessageId2AddUserVersion(builder *flatbuffers.Builder, userVersion uint16) {
	builder.PrependUint16Slot(3, userVersion, 0)
}
func MessageId2AddSuffix(builder *flatbuffers.Builder, suffix MessageSuffix) {
	builder.PrependByteSlot(4, byte(suffix), 0)
}
func MessageId2End(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
