// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MessageEvent2T struct {
	ChatId *MessageId2T `json:"chat_id"`
	ReactionId string `json:"reaction_id"`
	SenderId uint64 `json:"sender_id"`
	SenderTag string `json:"sender_tag"`
	MessageId string `json:"message_id"`
	Root string `json:"root"`
	Tag string `json:"tag"`
	Timestamp int64 `json:"timestamp"`
	ForwardedFrom uint64 `json:"forwarded_from"`
	ForwardedFromTag string `json:"forwarded_from_tag"`
	Nodes []uint64 `json:"nodes"`
	Replies []string `json:"replies"`
	Txt string `json:"txt"`
	MediaRef *MediaReferenceT `json:"media_ref"`
	PaymentRef *MediaReferenceT `json:"payment_ref"`
	Emoji string `json:"emoji"`
	Sniper *SniperT `json:"sniper"`
}

func (t *MessageEvent2T) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	chatIdOffset := t.ChatId.Pack(builder)
	reactionIdOffset := flatbuffers.UOffsetT(0)
	if t.ReactionId != "" {
		reactionIdOffset = builder.CreateString(t.ReactionId)
	}
	senderTagOffset := flatbuffers.UOffsetT(0)
	if t.SenderTag != "" {
		senderTagOffset = builder.CreateString(t.SenderTag)
	}
	messageIdOffset := flatbuffers.UOffsetT(0)
	if t.MessageId != "" {
		messageIdOffset = builder.CreateString(t.MessageId)
	}
	rootOffset := flatbuffers.UOffsetT(0)
	if t.Root != "" {
		rootOffset = builder.CreateString(t.Root)
	}
	tagOffset := flatbuffers.UOffsetT(0)
	if t.Tag != "" {
		tagOffset = builder.CreateString(t.Tag)
	}
	forwardedFromTagOffset := flatbuffers.UOffsetT(0)
	if t.ForwardedFromTag != "" {
		forwardedFromTagOffset = builder.CreateString(t.ForwardedFromTag)
	}
	nodesOffset := flatbuffers.UOffsetT(0)
	if t.Nodes != nil {
		nodesLength := len(t.Nodes)
		MessageEvent2StartNodesVector(builder, nodesLength)
		for j := nodesLength - 1; j >= 0; j-- {
			builder.PrependUint64(t.Nodes[j])
		}
		nodesOffset = builder.EndVector(nodesLength)
	}
	repliesOffset := flatbuffers.UOffsetT(0)
	if t.Replies != nil {
		repliesLength := len(t.Replies)
		repliesOffsets := make([]flatbuffers.UOffsetT, repliesLength)
		for j := 0; j < repliesLength; j++ {
			repliesOffsets[j] = builder.CreateString(t.Replies[j])
		}
		MessageEvent2StartRepliesVector(builder, repliesLength)
		for j := repliesLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(repliesOffsets[j])
		}
		repliesOffset = builder.EndVector(repliesLength)
	}
	txtOffset := flatbuffers.UOffsetT(0)
	if t.Txt != "" {
		txtOffset = builder.CreateString(t.Txt)
	}
	mediaRefOffset := t.MediaRef.Pack(builder)
	paymentRefOffset := t.PaymentRef.Pack(builder)
	emojiOffset := flatbuffers.UOffsetT(0)
	if t.Emoji != "" {
		emojiOffset = builder.CreateString(t.Emoji)
	}
	sniperOffset := t.Sniper.Pack(builder)
	MessageEvent2Start(builder)
	MessageEvent2AddChatId(builder, chatIdOffset)
	MessageEvent2AddReactionId(builder, reactionIdOffset)
	MessageEvent2AddSenderId(builder, t.SenderId)
	MessageEvent2AddSenderTag(builder, senderTagOffset)
	MessageEvent2AddMessageId(builder, messageIdOffset)
	MessageEvent2AddRoot(builder, rootOffset)
	MessageEvent2AddTag(builder, tagOffset)
	MessageEvent2AddTimestamp(builder, t.Timestamp)
	MessageEvent2AddForwardedFrom(builder, t.ForwardedFrom)
	MessageEvent2AddForwardedFromTag(builder, forwardedFromTagOffset)
	MessageEvent2AddNodes(builder, nodesOffset)
	MessageEvent2AddReplies(builder, repliesOffset)
	MessageEvent2AddTxt(builder, txtOffset)
	MessageEvent2AddMediaRef(builder, mediaRefOffset)
	MessageEvent2AddPaymentRef(builder, paymentRefOffset)
	MessageEvent2AddEmoji(builder, emojiOffset)
	MessageEvent2AddSniper(builder, sniperOffset)
	return MessageEvent2End(builder)
}

func (rcv *MessageEvent2) UnPackTo(t *MessageEvent2T) {
	t.ChatId = rcv.ChatId(nil).UnPack()
	t.ReactionId = string(rcv.ReactionId())
	t.SenderId = rcv.SenderId()
	t.SenderTag = string(rcv.SenderTag())
	t.MessageId = string(rcv.MessageId())
	t.Root = string(rcv.Root())
	t.Tag = string(rcv.Tag())
	t.Timestamp = rcv.Timestamp()
	t.ForwardedFrom = rcv.ForwardedFrom()
	t.ForwardedFromTag = string(rcv.ForwardedFromTag())
	nodesLength := rcv.NodesLength()
	t.Nodes = make([]uint64, nodesLength)
	for j := 0; j < nodesLength; j++ {
		t.Nodes[j] = rcv.Nodes(j)
	}
	repliesLength := rcv.RepliesLength()
	t.Replies = make([]string, repliesLength)
	for j := 0; j < repliesLength; j++ {
		t.Replies[j] = string(rcv.Replies(j))
	}
	t.Txt = string(rcv.Txt())
	t.MediaRef = rcv.MediaRef(nil).UnPack()
	t.PaymentRef = rcv.PaymentRef(nil).UnPack()
	t.Emoji = string(rcv.Emoji())
	t.Sniper = rcv.Sniper(nil).UnPack()
}

func (rcv *MessageEvent2) UnPack() *MessageEvent2T {
	if rcv == nil {
		return nil
	}
	t := &MessageEvent2T{}
	rcv.UnPackTo(t)
	return t
}

type MessageEvent2 struct {
	_tab flatbuffers.Table
}

func GetRootAsMessageEvent2(buf []byte, offset flatbuffers.UOffsetT) *MessageEvent2 {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MessageEvent2{}
	x.Init(buf, n+offset)
	return x
}

func FinishMessageEvent2Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMessageEvent2(buf []byte, offset flatbuffers.UOffsetT) *MessageEvent2 {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MessageEvent2{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMessageEvent2Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MessageEvent2) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MessageEvent2) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MessageEvent2) ChatId(obj *MessageId2) *MessageId2 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(MessageId2)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *MessageEvent2) ReactionId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MessageEvent2) SenderId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MessageEvent2) MutateSenderId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *MessageEvent2) SenderTag() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MessageEvent2) MessageId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MessageEvent2) Root() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MessageEvent2) Tag() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MessageEvent2) Timestamp() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MessageEvent2) MutateTimestamp(n int64) bool {
	return rcv._tab.MutateInt64Slot(18, n)
}

func (rcv *MessageEvent2) ForwardedFrom() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MessageEvent2) MutateForwardedFrom(n uint64) bool {
	return rcv._tab.MutateUint64Slot(20, n)
}

func (rcv *MessageEvent2) ForwardedFromTag() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MessageEvent2) Nodes(j int) uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *MessageEvent2) NodesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MessageEvent2) MutateNodes(j int, n uint64) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateUint64(a+flatbuffers.UOffsetT(j*8), n)
	}
	return false
}

func (rcv *MessageEvent2) Replies(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *MessageEvent2) RepliesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MessageEvent2) Txt() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MessageEvent2) MediaRef(obj *MediaReference) *MediaReference {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(MediaReference)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *MessageEvent2) PaymentRef(obj *MediaReference) *MediaReference {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(MediaReference)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *MessageEvent2) Emoji() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(34))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MessageEvent2) Sniper(obj *Sniper) *Sniper {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(36))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Sniper)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func MessageEvent2Start(builder *flatbuffers.Builder) {
	builder.StartObject(17)
}
func MessageEvent2AddChatId(builder *flatbuffers.Builder, chatId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(chatId), 0)
}
func MessageEvent2AddReactionId(builder *flatbuffers.Builder, reactionId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(reactionId), 0)
}
func MessageEvent2AddSenderId(builder *flatbuffers.Builder, senderId uint64) {
	builder.PrependUint64Slot(2, senderId, 0)
}
func MessageEvent2AddSenderTag(builder *flatbuffers.Builder, senderTag flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(senderTag), 0)
}
func MessageEvent2AddMessageId(builder *flatbuffers.Builder, messageId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(messageId), 0)
}
func MessageEvent2AddRoot(builder *flatbuffers.Builder, root flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(root), 0)
}
func MessageEvent2AddTag(builder *flatbuffers.Builder, tag flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(tag), 0)
}
func MessageEvent2AddTimestamp(builder *flatbuffers.Builder, timestamp int64) {
	builder.PrependInt64Slot(7, timestamp, 0)
}
func MessageEvent2AddForwardedFrom(builder *flatbuffers.Builder, forwardedFrom uint64) {
	builder.PrependUint64Slot(8, forwardedFrom, 0)
}
func MessageEvent2AddForwardedFromTag(builder *flatbuffers.Builder, forwardedFromTag flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(forwardedFromTag), 0)
}
func MessageEvent2AddNodes(builder *flatbuffers.Builder, nodes flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(10, flatbuffers.UOffsetT(nodes), 0)
}
func MessageEvent2StartNodesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func MessageEvent2AddReplies(builder *flatbuffers.Builder, replies flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(11, flatbuffers.UOffsetT(replies), 0)
}
func MessageEvent2StartRepliesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func MessageEvent2AddTxt(builder *flatbuffers.Builder, txt flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(12, flatbuffers.UOffsetT(txt), 0)
}
func MessageEvent2AddMediaRef(builder *flatbuffers.Builder, mediaRef flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(13, flatbuffers.UOffsetT(mediaRef), 0)
}
func MessageEvent2AddPaymentRef(builder *flatbuffers.Builder, paymentRef flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(14, flatbuffers.UOffsetT(paymentRef), 0)
}
func MessageEvent2AddEmoji(builder *flatbuffers.Builder, emoji flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(15, flatbuffers.UOffsetT(emoji), 0)
}
func MessageEvent2AddSniper(builder *flatbuffers.Builder, sniper flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(16, flatbuffers.UOffsetT(sniper), 0)
}
func MessageEvent2End(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
