// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MessageIdT struct {
	Prefix IdKind `json:"prefix"`
	Room *RoomT `json:"room"`
	TxVersion []byte `json:"tx_version"`
	UserVersion uint16 `json:"user_version"`
	Suffix MessageSuffix `json:"suffix"`
}

func (t *MessageIdT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	roomOffset := t.Room.Pack(builder)
	txVersionOffset := flatbuffers.UOffsetT(0)
	if t.TxVersion != nil {
		txVersionOffset = builder.CreateByteString(t.TxVersion)
	}
	MessageIdStart(builder)
	MessageIdAddPrefix(builder, t.Prefix)
	MessageIdAddRoom(builder, roomOffset)
	MessageIdAddTxVersion(builder, txVersionOffset)
	MessageIdAddUserVersion(builder, t.UserVersion)
	MessageIdAddSuffix(builder, t.Suffix)
	return MessageIdEnd(builder)
}

func (rcv *MessageId) UnPackTo(t *MessageIdT) {
	t.Prefix = rcv.Prefix()
	t.Room = rcv.Room(nil).UnPack()
	t.TxVersion = rcv.TxVersionBytes()
	t.UserVersion = rcv.UserVersion()
	t.Suffix = rcv.Suffix()
}

func (rcv *MessageId) UnPack() *MessageIdT {
	if rcv == nil {
		return nil
	}
	t := &MessageIdT{}
	rcv.UnPackTo(t)
	return t
}

type MessageId struct {
	_tab flatbuffers.Table
}

func GetRootAsMessageId(buf []byte, offset flatbuffers.UOffsetT) *MessageId {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MessageId{}
	x.Init(buf, n+offset)
	return x
}

func FinishMessageIdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMessageId(buf []byte, offset flatbuffers.UOffsetT) *MessageId {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MessageId{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMessageIdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MessageId) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MessageId) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MessageId) Prefix() IdKind {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return IdKind(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *MessageId) MutatePrefix(n IdKind) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *MessageId) Room(obj *Room) *Room {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Room)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *MessageId) TxVersion(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *MessageId) TxVersionLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MessageId) TxVersionBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MessageId) MutateTxVersion(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *MessageId) UserVersion() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MessageId) MutateUserVersion(n uint16) bool {
	return rcv._tab.MutateUint16Slot(10, n)
}

func (rcv *MessageId) Suffix() MessageSuffix {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return MessageSuffix(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *MessageId) MutateSuffix(n MessageSuffix) bool {
	return rcv._tab.MutateByteSlot(12, byte(n))
}

func MessageIdStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func MessageIdAddPrefix(builder *flatbuffers.Builder, prefix IdKind) {
	builder.PrependByteSlot(0, byte(prefix), 0)
}
func MessageIdAddRoom(builder *flatbuffers.Builder, room flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(room), 0)
}
func MessageIdAddTxVersion(builder *flatbuffers.Builder, txVersion flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(txVersion), 0)
}
func MessageIdStartTxVersionVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func MessageIdAddUserVersion(builder *flatbuffers.Builder, userVersion uint16) {
	builder.PrependUint16Slot(3, userVersion, 0)
}
func MessageIdAddSuffix(builder *flatbuffers.Builder, suffix MessageSuffix) {
	builder.PrependByteSlot(4, byte(suffix), 0)
}
func MessageIdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
