// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import "strconv"

type NodeCommand byte

const (
	NodeCommandDisconnectionConfirmation NodeCommand = 0
	NodeCommandConnectionConfirmation    NodeCommand = 1
	NodeCommandNodeUpdate                NodeCommand = 2
)

var EnumNamesNodeCommand = map[NodeCommand]string{
	NodeCommandDisconnectionConfirmation: "DisconnectionConfirmation",
	NodeCommandConnectionConfirmation:    "ConnectionConfirmation",
	NodeCommandNodeUpdate:                "NodeUpdate",
}

var EnumValuesNodeCommand = map[string]NodeCommand{
	"DisconnectionConfirmation": NodeCommandDisconnectionConfirmation,
	"ConnectionConfirmation":    NodeCommandConnectionConfirmation,
	"NodeUpdate":                NodeCommandNodeUpdate,
}

func (v NodeCommand) String() string {
	if s, ok := EnumNamesNodeCommand[v]; ok {
		return s
	}
	return "NodeCommand(" + strconv.FormatInt(int64(v), 10) + ")"
}
