// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type NotificationsT struct {
	SenderName string `json:"sender_name"`
	SenderId uint64 `json:"sender_id"`
	Root string `json:"root"`
	SenderMediaId string `json:"sender_media_id"`
	GroupMediaId string `json:"group_media_id"`
	Title string `json:"title"`
	Body string `json:"body"`
	IsGroup bool `json:"is_group"`
	Tokens []string `json:"tokens"`
}

func (t *NotificationsT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	senderNameOffset := flatbuffers.UOffsetT(0)
	if t.SenderName != "" {
		senderNameOffset = builder.CreateString(t.SenderName)
	}
	rootOffset := flatbuffers.UOffsetT(0)
	if t.Root != "" {
		rootOffset = builder.CreateString(t.Root)
	}
	senderMediaIdOffset := flatbuffers.UOffsetT(0)
	if t.SenderMediaId != "" {
		senderMediaIdOffset = builder.CreateString(t.SenderMediaId)
	}
	groupMediaIdOffset := flatbuffers.UOffsetT(0)
	if t.GroupMediaId != "" {
		groupMediaIdOffset = builder.CreateString(t.GroupMediaId)
	}
	titleOffset := flatbuffers.UOffsetT(0)
	if t.Title != "" {
		titleOffset = builder.CreateString(t.Title)
	}
	bodyOffset := flatbuffers.UOffsetT(0)
	if t.Body != "" {
		bodyOffset = builder.CreateString(t.Body)
	}
	tokensOffset := flatbuffers.UOffsetT(0)
	if t.Tokens != nil {
		tokensLength := len(t.Tokens)
		tokensOffsets := make([]flatbuffers.UOffsetT, tokensLength)
		for j := 0; j < tokensLength; j++ {
			tokensOffsets[j] = builder.CreateString(t.Tokens[j])
		}
		NotificationsStartTokensVector(builder, tokensLength)
		for j := tokensLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(tokensOffsets[j])
		}
		tokensOffset = builder.EndVector(tokensLength)
	}
	NotificationsStart(builder)
	NotificationsAddSenderName(builder, senderNameOffset)
	NotificationsAddSenderId(builder, t.SenderId)
	NotificationsAddRoot(builder, rootOffset)
	NotificationsAddSenderMediaId(builder, senderMediaIdOffset)
	NotificationsAddGroupMediaId(builder, groupMediaIdOffset)
	NotificationsAddTitle(builder, titleOffset)
	NotificationsAddBody(builder, bodyOffset)
	NotificationsAddIsGroup(builder, t.IsGroup)
	NotificationsAddTokens(builder, tokensOffset)
	return NotificationsEnd(builder)
}

func (rcv *Notifications) UnPackTo(t *NotificationsT) {
	t.SenderName = string(rcv.SenderName())
	t.SenderId = rcv.SenderId()
	t.Root = string(rcv.Root())
	t.SenderMediaId = string(rcv.SenderMediaId())
	t.GroupMediaId = string(rcv.GroupMediaId())
	t.Title = string(rcv.Title())
	t.Body = string(rcv.Body())
	t.IsGroup = rcv.IsGroup()
	tokensLength := rcv.TokensLength()
	t.Tokens = make([]string, tokensLength)
	for j := 0; j < tokensLength; j++ {
		t.Tokens[j] = string(rcv.Tokens(j))
	}
}

func (rcv *Notifications) UnPack() *NotificationsT {
	if rcv == nil {
		return nil
	}
	t := &NotificationsT{}
	rcv.UnPackTo(t)
	return t
}

type Notifications struct {
	_tab flatbuffers.Table
}

func GetRootAsNotifications(buf []byte, offset flatbuffers.UOffsetT) *Notifications {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Notifications{}
	x.Init(buf, n+offset)
	return x
}

func FinishNotificationsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsNotifications(buf []byte, offset flatbuffers.UOffsetT) *Notifications {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Notifications{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedNotificationsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Notifications) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Notifications) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Notifications) SenderName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Notifications) SenderId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Notifications) MutateSenderId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *Notifications) Root() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Notifications) SenderMediaId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Notifications) GroupMediaId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Notifications) Title() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Notifications) Body() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Notifications) IsGroup() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *Notifications) MutateIsGroup(n bool) bool {
	return rcv._tab.MutateBoolSlot(18, n)
}

func (rcv *Notifications) Tokens(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *Notifications) TokensLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func NotificationsStart(builder *flatbuffers.Builder) {
	builder.StartObject(9)
}
func NotificationsAddSenderName(builder *flatbuffers.Builder, senderName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(senderName), 0)
}
func NotificationsAddSenderId(builder *flatbuffers.Builder, senderId uint64) {
	builder.PrependUint64Slot(1, senderId, 0)
}
func NotificationsAddRoot(builder *flatbuffers.Builder, root flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(root), 0)
}
func NotificationsAddSenderMediaId(builder *flatbuffers.Builder, senderMediaId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(senderMediaId), 0)
}
func NotificationsAddGroupMediaId(builder *flatbuffers.Builder, groupMediaId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(groupMediaId), 0)
}
func NotificationsAddTitle(builder *flatbuffers.Builder, title flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(title), 0)
}
func NotificationsAddBody(builder *flatbuffers.Builder, body flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(body), 0)
}
func NotificationsAddIsGroup(builder *flatbuffers.Builder, isGroup bool) {
	builder.PrependBoolSlot(7, isGroup, false)
}
func NotificationsAddTokens(builder *flatbuffers.Builder, tokens flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(tokens), 0)
}
func NotificationsStartTokensVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func NotificationsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
