// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PartialTxT struct {
	PartialTx []byte `json:"partial_tx"`
	PartialTxid []byte `json:"partial_txid"`
	InputSats uint64 `json:"input_sats"`
}

func (t *PartialTxT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	partialTxOffset := flatbuffers.UOffsetT(0)
	if t.PartialTx != nil {
		partialTxOffset = builder.CreateByteString(t.PartialTx)
	}
	partialTxidOffset := flatbuffers.UOffsetT(0)
	if t.PartialTxid != nil {
		partialTxidOffset = builder.CreateByteString(t.PartialTxid)
	}
	PartialTxStart(builder)
	PartialTxAddPartialTx(builder, partialTxOffset)
	PartialTxAddPartialTxid(builder, partialTxidOffset)
	PartialTxAddInputSats(builder, t.InputSats)
	return PartialTxEnd(builder)
}

func (rcv *PartialTx) UnPackTo(t *PartialTxT) {
	t.PartialTx = rcv.PartialTxBytes()
	t.PartialTxid = rcv.PartialTxidBytes()
	t.InputSats = rcv.InputSats()
}

func (rcv *PartialTx) UnPack() *PartialTxT {
	if rcv == nil {
		return nil
	}
	t := &PartialTxT{}
	rcv.UnPackTo(t)
	return t
}

type PartialTx struct {
	_tab flatbuffers.Table
}

func GetRootAsPartialTx(buf []byte, offset flatbuffers.UOffsetT) *PartialTx {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PartialTx{}
	x.Init(buf, n+offset)
	return x
}

func FinishPartialTxBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPartialTx(buf []byte, offset flatbuffers.UOffsetT) *PartialTx {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PartialTx{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPartialTxBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PartialTx) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PartialTx) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PartialTx) PartialTx(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *PartialTx) PartialTxLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *PartialTx) PartialTxBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PartialTx) MutatePartialTx(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *PartialTx) PartialTxid(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *PartialTx) PartialTxidLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *PartialTx) PartialTxidBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PartialTx) MutatePartialTxid(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *PartialTx) InputSats() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PartialTx) MutateInputSats(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func PartialTxStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func PartialTxAddPartialTx(builder *flatbuffers.Builder, partialTx flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(partialTx), 0)
}
func PartialTxStartPartialTxVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func PartialTxAddPartialTxid(builder *flatbuffers.Builder, partialTxid flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(partialTxid), 0)
}
func PartialTxStartPartialTxidVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func PartialTxAddInputSats(builder *flatbuffers.Builder, inputSats uint64) {
	builder.PrependUint64Slot(2, inputSats, 0)
}
func PartialTxEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
