// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import "strconv"

type PayloadKind byte

const (
	PayloadKindBoostResult        PayloadKind = 0
	PayloadKindPayment            PayloadKind = 1
	PayloadKindBoostRequestResult PayloadKind = 2
	PayloadKindText               PayloadKind = 3
	PayloadKindMediaUpload        PayloadKind = 4
)

var EnumNamesPayloadKind = map[PayloadKind]string{
	PayloadKindBoostResult:        "BoostResult",
	PayloadKindPayment:            "Payment",
	PayloadKindBoostRequestResult: "BoostRequestResult",
	PayloadKindText:               "Text",
	PayloadKindMediaUpload:        "MediaUpload",
}

var EnumValuesPayloadKind = map[string]PayloadKind{
	"BoostResult":        PayloadKindBoostResult,
	"Payment":            PayloadKindPayment,
	"BoostRequestResult": PayloadKindBoostRequestResult,
	"Text":               PayloadKindText,
	"MediaUpload":        PayloadKindMediaUpload,
}

func (v PayloadKind) String() string {
	if s, ok := EnumNamesPayloadKind[v]; ok {
		return s
	}
	return "PayloadKind(" + strconv.FormatInt(int64(v), 10) + ")"
}
