// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PaymentPush struct {
	_tab flatbuffers.Table
}

func GetRootAsPaymentPush(buf []byte, offset flatbuffers.UOffsetT) *PaymentPush {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PaymentPush{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsPaymentPush(buf []byte, offset flatbuffers.UOffsetT) *PaymentPush {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PaymentPush{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *PaymentPush) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PaymentPush) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PaymentPush) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PaymentPush) TempId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func PaymentPushStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PaymentPushAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func PaymentPushAddTempId(builder *flatbuffers.Builder, tempId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(tempId), 0)
}
func PaymentPushEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
