// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PaymentPushT struct {
	Id string `json:"id"`
	TempId string `json:"temp_id"`
}

func (t *PaymentPushT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	idOffset := flatbuffers.UOffsetT(0)
	if t.Id != "" {
		idOffset = builder.CreateString(t.Id)
	}
	tempIdOffset := flatbuffers.UOffsetT(0)
	if t.TempId != "" {
		tempIdOffset = builder.CreateString(t.TempId)
	}
	PaymentPushStart(builder)
	PaymentPushAddId(builder, idOffset)
	PaymentPushAddTempId(builder, tempIdOffset)
	return PaymentPushEnd(builder)
}

func (rcv *PaymentPush) UnPackTo(t *PaymentPushT) {
	t.Id = string(rcv.Id())
	t.TempId = string(rcv.TempId())
}

func (rcv *PaymentPush) UnPack() *PaymentPushT {
	if rcv == nil {
		return nil
	}
	t := &PaymentPushT{}
	rcv.UnPackTo(t)
	return t
}

type PaymentPush struct {
	_tab flatbuffers.Table
}

func GetRootAsPaymentPush(buf []byte, offset flatbuffers.UOffsetT) *PaymentPush {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PaymentPush{}
	x.Init(buf, n+offset)
	return x
}

func FinishPaymentPushBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPaymentPush(buf []byte, offset flatbuffers.UOffsetT) *PaymentPush {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PaymentPush{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPaymentPushBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PaymentPush) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PaymentPush) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PaymentPush) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PaymentPush) TempId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func PaymentPushStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PaymentPushAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func PaymentPushAddTempId(builder *flatbuffers.Builder, tempId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(tempId), 0)
}
func PaymentPushEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
