// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PushIdT struct {
	U32 uint32 `json:"u32"`
	Timestamp int64 `json:"timestamp"`
	Place uint16 `json:"place"`
	Root string `json:"root"`
	Device uint32 `json:"device"`
}

func (t *PushIdT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	rootOffset := flatbuffers.UOffsetT(0)
	if t.Root != "" {
		rootOffset = builder.CreateString(t.Root)
	}
	PushIdStart(builder)
	PushIdAddU32(builder, t.U32)
	PushIdAddTimestamp(builder, t.Timestamp)
	PushIdAddPlace(builder, t.Place)
	PushIdAddRoot(builder, rootOffset)
	PushIdAddDevice(builder, t.Device)
	return PushIdEnd(builder)
}

func (rcv *PushId) UnPackTo(t *PushIdT) {
	t.U32 = rcv.U32()
	t.Timestamp = rcv.Timestamp()
	t.Place = rcv.Place()
	t.Root = string(rcv.Root())
	t.Device = rcv.Device()
}

func (rcv *PushId) UnPack() *PushIdT {
	if rcv == nil {
		return nil
	}
	t := &PushIdT{}
	rcv.UnPackTo(t)
	return t
}

type PushId struct {
	_tab flatbuffers.Table
}

func GetRootAsPushId(buf []byte, offset flatbuffers.UOffsetT) *PushId {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PushId{}
	x.Init(buf, n+offset)
	return x
}

func FinishPushIdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPushId(buf []byte, offset flatbuffers.UOffsetT) *PushId {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PushId{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPushIdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PushId) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PushId) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PushId) U32() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PushId) MutateU32(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *PushId) Timestamp() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PushId) MutateTimestamp(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *PushId) Place() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PushId) MutatePlace(n uint16) bool {
	return rcv._tab.MutateUint16Slot(8, n)
}

func (rcv *PushId) Root() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PushId) Device() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PushId) MutateDevice(n uint32) bool {
	return rcv._tab.MutateUint32Slot(12, n)
}

func PushIdStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func PushIdAddU32(builder *flatbuffers.Builder, u32 uint32) {
	builder.PrependUint32Slot(0, u32, 0)
}
func PushIdAddTimestamp(builder *flatbuffers.Builder, timestamp int64) {
	builder.PrependInt64Slot(1, timestamp, 0)
}
func PushIdAddPlace(builder *flatbuffers.Builder, place uint16) {
	builder.PrependUint16Slot(2, place, 0)
}
func PushIdAddRoot(builder *flatbuffers.Builder, root flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(root), 0)
}
func PushIdAddDevice(builder *flatbuffers.Builder, device uint32) {
	builder.PrependUint32Slot(4, device, 0)
}
func PushIdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
