// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PushRequestT struct {
	RawNodeId []byte `json:"raw_node_id"`
	Dev uint32 `json:"dev"`
	Type byte `json:"type"`
	Payload []byte `json:"payload"`
}

func (t *PushRequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	rawNodeIdOffset := flatbuffers.UOffsetT(0)
	if t.RawNodeId != nil {
		rawNodeIdOffset = builder.CreateByteString(t.RawNodeId)
	}
	payloadOffset := flatbuffers.UOffsetT(0)
	if t.Payload != nil {
		payloadOffset = builder.CreateByteString(t.Payload)
	}
	PushRequestStart(builder)
	PushRequestAddRawNodeId(builder, rawNodeIdOffset)
	PushRequestAddDev(builder, t.Dev)
	PushRequestAddType(builder, t.Type)
	PushRequestAddPayload(builder, payloadOffset)
	return PushRequestEnd(builder)
}

func (rcv *PushRequest) UnPackTo(t *PushRequestT) {
	t.RawNodeId = rcv.RawNodeIdBytes()
	t.Dev = rcv.Dev()
	t.Type = rcv.Type()
	t.Payload = rcv.PayloadBytes()
}

func (rcv *PushRequest) UnPack() *PushRequestT {
	if rcv == nil {
		return nil
	}
	t := &PushRequestT{}
	rcv.UnPackTo(t)
	return t
}

type PushRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsPushRequest(buf []byte, offset flatbuffers.UOffsetT) *PushRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PushRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishPushRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPushRequest(buf []byte, offset flatbuffers.UOffsetT) *PushRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PushRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPushRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PushRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PushRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PushRequest) RawNodeId(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *PushRequest) RawNodeIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *PushRequest) RawNodeIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PushRequest) MutateRawNodeId(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *PushRequest) Dev() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PushRequest) MutateDev(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *PushRequest) Type() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PushRequest) MutateType(n byte) bool {
	return rcv._tab.MutateByteSlot(8, n)
}

func (rcv *PushRequest) Payload(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *PushRequest) PayloadLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *PushRequest) PayloadBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PushRequest) MutatePayload(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func PushRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func PushRequestAddRawNodeId(builder *flatbuffers.Builder, rawNodeId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(rawNodeId), 0)
}
func PushRequestStartRawNodeIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func PushRequestAddDev(builder *flatbuffers.Builder, dev uint32) {
	builder.PrependUint32Slot(1, dev, 0)
}
func PushRequestAddType(builder *flatbuffers.Builder, type_ byte) {
	builder.PrependByteSlot(2, type_, 0)
}
func PushRequestAddPayload(builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(payload), 0)
}
func PushRequestStartPayloadVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func PushRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
