// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RoomT struct {
	Prefix IdKind `json:"prefix"`
	Cluster uint16 `json:"cluster"`
	Primary uint64 `json:"primary"`
	Secondary uint64 `json:"secondary"`
}

func (t *RoomT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	RoomStart(builder)
	RoomAddPrefix(builder, t.Prefix)
	RoomAddCluster(builder, t.Cluster)
	RoomAddPrimary(builder, t.Primary)
	RoomAddSecondary(builder, t.Secondary)
	return RoomEnd(builder)
}

func (rcv *Room) UnPackTo(t *RoomT) {
	t.Prefix = rcv.Prefix()
	t.Cluster = rcv.Cluster()
	t.Primary = rcv.Primary()
	t.Secondary = rcv.Secondary()
}

func (rcv *Room) UnPack() *RoomT {
	if rcv == nil {
		return nil
	}
	t := &RoomT{}
	rcv.UnPackTo(t)
	return t
}

type Room struct {
	_tab flatbuffers.Table
}

func GetRootAsRoom(buf []byte, offset flatbuffers.UOffsetT) *Room {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Room{}
	x.Init(buf, n+offset)
	return x
}

func FinishRoomBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRoom(buf []byte, offset flatbuffers.UOffsetT) *Room {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Room{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRoomBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Room) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Room) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Room) Prefix() IdKind {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return IdKind(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Room) MutatePrefix(n IdKind) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *Room) Cluster() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Room) MutateCluster(n uint16) bool {
	return rcv._tab.MutateUint16Slot(6, n)
}

func (rcv *Room) Primary() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Room) MutatePrimary(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *Room) Secondary() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Room) MutateSecondary(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func RoomStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func RoomAddPrefix(builder *flatbuffers.Builder, prefix IdKind) {
	builder.PrependByteSlot(0, byte(prefix), 0)
}
func RoomAddCluster(builder *flatbuffers.Builder, cluster uint16) {
	builder.PrependUint16Slot(1, cluster, 0)
}
func RoomAddPrimary(builder *flatbuffers.Builder, primary uint64) {
	builder.PrependUint64Slot(2, primary, 0)
}
func RoomAddSecondary(builder *flatbuffers.Builder, secondary uint64) {
	builder.PrependUint64Slot(3, secondary, 0)
}
func RoomEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
