// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Room2T struct {
	Prefix IdKind `json:"prefix"`
	Primary uint64 `json:"primary"`
	Secondary uint64 `json:"secondary"`
	Cluster uint16 `json:"cluster"`
}

func (t *Room2T) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	Room2Start(builder)
	Room2AddPrefix(builder, t.Prefix)
	Room2AddPrimary(builder, t.Primary)
	Room2AddSecondary(builder, t.Secondary)
	Room2AddCluster(builder, t.Cluster)
	return Room2End(builder)
}

func (rcv *Room2) UnPackTo(t *Room2T) {
	t.Prefix = rcv.Prefix()
	t.Primary = rcv.Primary()
	t.Secondary = rcv.Secondary()
	t.Cluster = rcv.Cluster()
}

func (rcv *Room2) UnPack() *Room2T {
	if rcv == nil {
		return nil
	}
	t := &Room2T{}
	rcv.UnPackTo(t)
	return t
}

type Room2 struct {
	_tab flatbuffers.Table
}

func GetRootAsRoom2(buf []byte, offset flatbuffers.UOffsetT) *Room2 {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Room2{}
	x.Init(buf, n+offset)
	return x
}

func FinishRoom2Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRoom2(buf []byte, offset flatbuffers.UOffsetT) *Room2 {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Room2{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRoom2Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Room2) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Room2) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Room2) Prefix() IdKind {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return IdKind(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Room2) MutatePrefix(n IdKind) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *Room2) Primary() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Room2) MutatePrimary(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *Room2) Secondary() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Room2) MutateSecondary(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *Room2) Cluster() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Room2) MutateCluster(n uint16) bool {
	return rcv._tab.MutateUint16Slot(10, n)
}

func Room2Start(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func Room2AddPrefix(builder *flatbuffers.Builder, prefix IdKind) {
	builder.PrependByteSlot(0, byte(prefix), 0)
}
func Room2AddPrimary(builder *flatbuffers.Builder, primary uint64) {
	builder.PrependUint64Slot(1, primary, 0)
}
func Room2AddSecondary(builder *flatbuffers.Builder, secondary uint64) {
	builder.PrependUint64Slot(2, secondary, 0)
}
func Room2AddCluster(builder *flatbuffers.Builder, cluster uint16) {
	builder.PrependUint16Slot(3, cluster, 0)
}
func Room2End(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
