// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ScrollRequestT struct {
	Before bool `json:"before"`
	Limit byte `json:"limit"`
	MessageId *MessageIdT `json:"message_id"`
}

func (t *ScrollRequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	messageIdOffset := t.MessageId.Pack(builder)
	ScrollRequestStart(builder)
	ScrollRequestAddBefore(builder, t.Before)
	ScrollRequestAddLimit(builder, t.Limit)
	ScrollRequestAddMessageId(builder, messageIdOffset)
	return ScrollRequestEnd(builder)
}

func (rcv *ScrollRequest) UnPackTo(t *ScrollRequestT) {
	t.Before = rcv.Before()
	t.Limit = rcv.Limit()
	t.MessageId = rcv.MessageId(nil).UnPack()
}

func (rcv *ScrollRequest) UnPack() *ScrollRequestT {
	if rcv == nil {
		return nil
	}
	t := &ScrollRequestT{}
	rcv.UnPackTo(t)
	return t
}

type ScrollRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsScrollRequest(buf []byte, offset flatbuffers.UOffsetT) *ScrollRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ScrollRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishScrollRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsScrollRequest(buf []byte, offset flatbuffers.UOffsetT) *ScrollRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ScrollRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedScrollRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ScrollRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ScrollRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ScrollRequest) Before() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ScrollRequest) MutateBefore(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *ScrollRequest) Limit() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ScrollRequest) MutateLimit(n byte) bool {
	return rcv._tab.MutateByteSlot(6, n)
}

func (rcv *ScrollRequest) MessageId(obj *MessageId) *MessageId {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(MessageId)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func ScrollRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ScrollRequestAddBefore(builder *flatbuffers.Builder, before bool) {
	builder.PrependBoolSlot(0, before, false)
}
func ScrollRequestAddLimit(builder *flatbuffers.Builder, limit byte) {
	builder.PrependByteSlot(1, limit, 0)
}
func ScrollRequestAddMessageId(builder *flatbuffers.Builder, messageId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(messageId), 0)
}
func ScrollRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
