// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ScrollRequest2T struct {
	MessageId *MessageId2T `json:"message_id"`
	Limit byte `json:"limit"`
	Before bool `json:"before"`
}

func (t *ScrollRequest2T) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	messageIdOffset := t.MessageId.Pack(builder)
	ScrollRequest2Start(builder)
	ScrollRequest2AddMessageId(builder, messageIdOffset)
	ScrollRequest2AddLimit(builder, t.Limit)
	ScrollRequest2AddBefore(builder, t.Before)
	return ScrollRequest2End(builder)
}

func (rcv *ScrollRequest2) UnPackTo(t *ScrollRequest2T) {
	t.MessageId = rcv.MessageId(nil).UnPack()
	t.Limit = rcv.Limit()
	t.Before = rcv.Before()
}

func (rcv *ScrollRequest2) UnPack() *ScrollRequest2T {
	if rcv == nil {
		return nil
	}
	t := &ScrollRequest2T{}
	rcv.UnPackTo(t)
	return t
}

type ScrollRequest2 struct {
	_tab flatbuffers.Table
}

func GetRootAsScrollRequest2(buf []byte, offset flatbuffers.UOffsetT) *ScrollRequest2 {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ScrollRequest2{}
	x.Init(buf, n+offset)
	return x
}

func FinishScrollRequest2Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsScrollRequest2(buf []byte, offset flatbuffers.UOffsetT) *ScrollRequest2 {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ScrollRequest2{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedScrollRequest2Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ScrollRequest2) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ScrollRequest2) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ScrollRequest2) MessageId(obj *MessageId2) *MessageId2 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(MessageId2)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ScrollRequest2) Limit() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ScrollRequest2) MutateLimit(n byte) bool {
	return rcv._tab.MutateByteSlot(6, n)
}

func (rcv *ScrollRequest2) Before() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ScrollRequest2) MutateBefore(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func ScrollRequest2Start(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ScrollRequest2AddMessageId(builder *flatbuffers.Builder, messageId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(messageId), 0)
}
func ScrollRequest2AddLimit(builder *flatbuffers.Builder, limit byte) {
	builder.PrependByteSlot(1, limit, 0)
}
func ScrollRequest2AddBefore(builder *flatbuffers.Builder, before bool) {
	builder.PrependBoolSlot(2, before, false)
}
func ScrollRequest2End(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
