// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SniperT struct {
	MediaRef *MediaReferenceT `json:"media_ref"`
	Sticks []*StickT `json:"sticks"`
	Ps *OffsetT `json:"ps"`
	Text string `json:"text"`
	Pdy float32 `json:"pdy"`
}

func (t *SniperT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	mediaRefOffset := t.MediaRef.Pack(builder)
	sticksOffset := flatbuffers.UOffsetT(0)
	if t.Sticks != nil {
		sticksLength := len(t.Sticks)
		sticksOffsets := make([]flatbuffers.UOffsetT, sticksLength)
		for j := 0; j < sticksLength; j++ {
			sticksOffsets[j] = t.Sticks[j].Pack(builder)
		}
		SniperStartSticksVector(builder, sticksLength)
		for j := sticksLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(sticksOffsets[j])
		}
		sticksOffset = builder.EndVector(sticksLength)
	}
	textOffset := flatbuffers.UOffsetT(0)
	if t.Text != "" {
		textOffset = builder.CreateString(t.Text)
	}
	SniperStart(builder)
	SniperAddMediaRef(builder, mediaRefOffset)
	SniperAddSticks(builder, sticksOffset)
	psOffset := t.Ps.Pack(builder)
	SniperAddPs(builder, psOffset)
	SniperAddText(builder, textOffset)
	SniperAddPdy(builder, t.Pdy)
	return SniperEnd(builder)
}

func (rcv *Sniper) UnPackTo(t *SniperT) {
	t.MediaRef = rcv.MediaRef(nil).UnPack()
	sticksLength := rcv.SticksLength()
	t.Sticks = make([]*StickT, sticksLength)
	for j := 0; j < sticksLength; j++ {
		x := Stick{}
		rcv.Sticks(&x, j)
		t.Sticks[j] = x.UnPack()
	}
	t.Ps = rcv.Ps(nil).UnPack()
	t.Text = string(rcv.Text())
	t.Pdy = rcv.Pdy()
}

func (rcv *Sniper) UnPack() *SniperT {
	if rcv == nil {
		return nil
	}
	t := &SniperT{}
	rcv.UnPackTo(t)
	return t
}

type Sniper struct {
	_tab flatbuffers.Table
}

func GetRootAsSniper(buf []byte, offset flatbuffers.UOffsetT) *Sniper {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Sniper{}
	x.Init(buf, n+offset)
	return x
}

func FinishSniperBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSniper(buf []byte, offset flatbuffers.UOffsetT) *Sniper {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Sniper{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSniperBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Sniper) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Sniper) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Sniper) MediaRef(obj *MediaReference) *MediaReference {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(MediaReference)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Sniper) Sticks(obj *Stick, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Sniper) SticksLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Sniper) Ps(obj *Offset) *Offset {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(Offset)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Sniper) Text() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Sniper) Pdy() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Sniper) MutatePdy(n float32) bool {
	return rcv._tab.MutateFloat32Slot(12, n)
}

func SniperStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func SniperAddMediaRef(builder *flatbuffers.Builder, mediaRef flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(mediaRef), 0)
}
func SniperAddSticks(builder *flatbuffers.Builder, sticks flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(sticks), 0)
}
func SniperStartSticksVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func SniperAddPs(builder *flatbuffers.Builder, ps flatbuffers.UOffsetT) {
	builder.PrependStructSlot(2, flatbuffers.UOffsetT(ps), 0)
}
func SniperAddText(builder *flatbuffers.Builder, text flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(text), 0)
}
func SniperAddPdy(builder *flatbuffers.Builder, pdy float32) {
	builder.PrependFloat32Slot(4, pdy, 0.0)
}
func SniperEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
