// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StickT struct {
	MediaRef *MediaReferenceT `json:"media_ref"`
	Emoji string `json:"emoji"`
	Pos *OffsetT `json:"pos"`
	InitSize *OffsetT `json:"init_size"`
	Rotation float32 `json:"rotation"`
	Scale float32 `json:"scale"`
}

func (t *StickT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	mediaRefOffset := t.MediaRef.Pack(builder)
	emojiOffset := flatbuffers.UOffsetT(0)
	if t.Emoji != "" {
		emojiOffset = builder.CreateString(t.Emoji)
	}
	StickStart(builder)
	StickAddMediaRef(builder, mediaRefOffset)
	StickAddEmoji(builder, emojiOffset)
	posOffset := t.Pos.Pack(builder)
	StickAddPos(builder, posOffset)
	initSizeOffset := t.InitSize.Pack(builder)
	StickAddInitSize(builder, initSizeOffset)
	StickAddRotation(builder, t.Rotation)
	StickAddScale(builder, t.Scale)
	return StickEnd(builder)
}

func (rcv *Stick) UnPackTo(t *StickT) {
	t.MediaRef = rcv.MediaRef(nil).UnPack()
	t.Emoji = string(rcv.Emoji())
	t.Pos = rcv.Pos(nil).UnPack()
	t.InitSize = rcv.InitSize(nil).UnPack()
	t.Rotation = rcv.Rotation()
	t.Scale = rcv.Scale()
}

func (rcv *Stick) UnPack() *StickT {
	if rcv == nil {
		return nil
	}
	t := &StickT{}
	rcv.UnPackTo(t)
	return t
}

type Stick struct {
	_tab flatbuffers.Table
}

func GetRootAsStick(buf []byte, offset flatbuffers.UOffsetT) *Stick {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Stick{}
	x.Init(buf, n+offset)
	return x
}

func FinishStickBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStick(buf []byte, offset flatbuffers.UOffsetT) *Stick {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Stick{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStickBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Stick) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Stick) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Stick) MediaRef(obj *MediaReference) *MediaReference {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(MediaReference)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Stick) Emoji() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Stick) Pos(obj *Offset) *Offset {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(Offset)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Stick) InitSize(obj *Offset) *Offset {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(Offset)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Stick) Rotation() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Stick) MutateRotation(n float32) bool {
	return rcv._tab.MutateFloat32Slot(12, n)
}

func (rcv *Stick) Scale() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Stick) MutateScale(n float32) bool {
	return rcv._tab.MutateFloat32Slot(14, n)
}

func StickStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func StickAddMediaRef(builder *flatbuffers.Builder, mediaRef flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(mediaRef), 0)
}
func StickAddEmoji(builder *flatbuffers.Builder, emoji flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(emoji), 0)
}
func StickAddPos(builder *flatbuffers.Builder, pos flatbuffers.UOffsetT) {
	builder.PrependStructSlot(2, flatbuffers.UOffsetT(pos), 0)
}
func StickAddInitSize(builder *flatbuffers.Builder, initSize flatbuffers.UOffsetT) {
	builder.PrependStructSlot(3, flatbuffers.UOffsetT(initSize), 0)
}
func StickAddRotation(builder *flatbuffers.Builder, rotation float32) {
	builder.PrependFloat32Slot(4, rotation, 0.0)
}
func StickAddScale(builder *flatbuffers.Builder, scale float32) {
	builder.PrependFloat32Slot(5, scale, 0.0)
}
func StickEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
