// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatgen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UserInfoT struct {
	Cluster uint16 `json:"cluster"`
	Device uint32 `json:"device"`
	Id uint64 `json:"id"`
}

func (t *UserInfoT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	UserInfoStart(builder)
	UserInfoAddCluster(builder, t.Cluster)
	UserInfoAddDevice(builder, t.Device)
	UserInfoAddId(builder, t.Id)
	return UserInfoEnd(builder)
}

func (rcv *UserInfo) UnPackTo(t *UserInfoT) {
	t.Cluster = rcv.Cluster()
	t.Device = rcv.Device()
	t.Id = rcv.Id()
}

func (rcv *UserInfo) UnPack() *UserInfoT {
	if rcv == nil {
		return nil
	}
	t := &UserInfoT{}
	rcv.UnPackTo(t)
	return t
}

type UserInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsUserInfo(buf []byte, offset flatbuffers.UOffsetT) *UserInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UserInfo{}
	x.Init(buf, n+offset)
	return x
}

func FinishUserInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsUserInfo(buf []byte, offset flatbuffers.UOffsetT) *UserInfo {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UserInfo{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedUserInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *UserInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UserInfo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UserInfo) Cluster() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *UserInfo) MutateCluster(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func (rcv *UserInfo) Device() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *UserInfo) MutateDevice(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *UserInfo) Id() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *UserInfo) MutateId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func UserInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func UserInfoAddCluster(builder *flatbuffers.Builder, cluster uint16) {
	builder.PrependUint16Slot(0, cluster, 0)
}
func UserInfoAddDevice(builder *flatbuffers.Builder, device uint32) {
	builder.PrependUint32Slot(1, device, 0)
}
func UserInfoAddId(builder *flatbuffers.Builder, id uint64) {
	builder.PrependUint64Slot(2, id, 0)
}
func UserInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
